### ISSUE TITLE
'FirebaseCore/FIRAnalyticsConfiguration.h' file not found on v5

### ISSUE THREAD

**Issue by stereodenis** [invertase/react-native-firebase#1106]
@chrisbianca 
![image](https://user-images.githubusercontent.com/1406461/40268151-3a6047ee-5b71-11e8-8673-e252a5423e6f.png)

```
PODS:
  - Firebase (5.0.1):
    - Firebase/Core (= 5.0.1)
  - Firebase/Auth (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.0.0)
  - Firebase/Core (5.0.1):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.0.0)
  - Firebase/CoreOnly (5.0.1):
    - FirebaseCore (= 5.0.1)
  - Firebase/Messaging (5.0.1):
    - Firebase/CoreOnly
    - FirebaseMessaging (= 3.0.0)
  - FirebaseAnalytics (5.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.0.0):
    - FirebaseCore (~> 5.0)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (5.0.1):
    - "GoogleToolboxForMac/NSData+zlib (~> 2.1)"
  - FirebaseInstanceID (3.0.0):
    - FirebaseCore (~> 5.0)
  - FirebaseMessaging (3.0.0):
    - FirebaseCore (~> 5.0)
    - FirebaseInstanceID (~> 3.0)
    - GoogleToolboxForMac/Logger (~> 2.1)
    - Protobuf (~> 3.1)
  - GoogleToolboxForMac/Defines (2.1.4)
  - GoogleToolboxForMac/Logger (2.1.4):
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - "GoogleToolboxForMac/NSData+zlib (2.1.4)":
    - GoogleToolboxForMac/Defines (= 2.1.4)
  - GTMSessionFetcher/Core (1.1.15)
  - nanopb (0.3.8):
    - nanopb/decode (= 0.3.8)
    - nanopb/encode (= 0.3.8)
  - nanopb/decode (0.3.8)
  - nanopb/encode (0.3.8)
  - Protobuf (3.5.0)
```
"react-native": "0.54.0"
"react-native-firebase": "^4.2.0"

What's wrong?

**Comment by NirpE** [comment]
I'm encountering the same issue, and known workarounds on this?

**Comment by jerinjohnk** [comment]
Was getting the same error. So as per the comment @dluksza in #1106
Updated podfile to use version **4.2.0** 
```
pod 'Firebase/Core','4.2.0'
pod 'Firebase/Messaging','4.2.0'
```
But this instead gave me following error while creating a debug build.
`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNFirebaseMessaging messaging:didRefreshRegistrationToken:]: unrecognized selector sent to instance 0x137ebbd20'`

**Comment by chrisbianca** [comment]
You need to make sure you are on:

Javascript:
`react-native-firebase`: v4.2.0

Pods:
`Firebase/Core`: v5+

This is explained in the v4.2.0 release notes.

Once you have updated your pods and npm libraries, please make sure you clean your build within XCode (I suggest restarting once you have), and then rebuilding.  This is definitely a case of npm/pods/Xcode getting out of sync and there are no issues when everything is correctly installed.

**Comment by jerinjohnk** [comment]
@chrisbianca  thanks. Did a `pod update` which somehow fixed the issue.

**Comment by vishal-android-freak** [comment]
I am facing

```'FirebaseCore/FirebaseCore.h not found```

I am on v4.2 and my pods are updated and are > 5.0

Any help?

**Comment by vishal-android-freak** [comment]
@rikur tried it couple of times. Same issue persists.

**Comment by NirpE** [comment]
I get 'FirebaseCore/FIRAnalyticsConfiguration.h' file not found when trying to archive. Deleted pods and node_modules and reinstalled them but didn't help.

**Comment by Porshe** [comment]
> FirebaseCore/FirebaseCore.h not found

when trying to archive.

**Comment by wanbok** [comment]
I got the same issue. This issue is not resolved yet.

**Comment by wanbok** [comment]
My solution is downgrade to `RNFirebase` to `4.1.0`, `Firebase/Core` and `Firebase/Message` to `~> 4.13`

**Comment by NirpE** [comment]
@wanbok if you archive app does everything work normally? Are you using Firebase Functions? Care to share your Podfile lines for all Firebase dependencies?

**Comment by zkrige** [comment]
`FirebaseCore/FirebaseCore.h not found`
same issue when trying to archive. Run on device works fine, only archive is failing

**Comment by Rojuinex** [comment]
How come this issue is closed? I have the same issue.  Doesn't seem resolved.

**Comment by soh335** [comment]
I add these lines into my podfile, and success to archive app.

```
  pre_install do |installer|
    if Dir.exists? "./Firebase"
      FileUtils.remove_entry_secure "./Firebase"
    end
  end
  post_install do |installer|
    # RNFirebase need FirebaseCore/FirebaseCore.h
    # but we use use_frameworks! so, Pods/Headers is empty.
    # RNFirebase also search header in ios/Firebase directory. so we copy FirebaseCore headers into this directory.
    FileUtils.mkdir_p "./Firebase"
    File.symlink "./../Pods/FirebaseCore/Firebase/Core/Public/", "./Firebase/FirebaseCore"
  end
```

**Comment by azraelx23** [comment]
yep same issue here

**Comment by pearlismylove** [comment]
Same here~

**Comment by oferRounds** [comment]
+

**Comment by testshallpasswork** [comment]
I have same issue that the author reported. I've tried clean & archive, `pod install` without `use_frameworks!` and restart Xcode. 

Podfile:
```
target '...' do
  use_frameworks!
    
  # Pods for AppCenter
  pod 'AppCenter/Crashes', '~> 1.4.0'
  pod 'AppCenterReactNativeShared', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.4.0'
  
  # Pod for Firebase
  pod 'Firebase/Core'
    
  platform :ios, '10.0'
end
```

react-native-firebase: 4.2.0
firebase-ios-sdk: v5

I am successfully running it on simulator.

**Comment by jerinjohnk** [comment]
React Native version: 0.55.4

**Comment by Benjuari** [comment]
This issue does not seem to be resolved, have not found a decent solution.

**Comment by aaronkchsu** [comment]
Hmmm same for me archive is failing, I can run the app on the simulator! It's been painful to try and fix haha! Help!

**Comment by oferRounds** [comment]
any solution? someone?

**Comment by vishal-android-freak** [comment]
@chrisbianca could you please update us on this? Apologies but my production release is pending because of this 😅

**Comment by vishal-android-freak** [comment]
I can confirm deleting pods folder, pod lock files and xcworkspace file, remove ```use_frameworks``` from Podfile and reinstalling has fixed the issue. Will observe for few days and revert if I see some changes. Thankyou @oferRounds  👍

**Comment by vishal-android-freak** [comment]
@Friis1978 remove ```use_frameworks!``` from pod file and delete Pods folder, lockfile xcworkspace, etc. and do ```pod install``` again

**Comment by vishal-android-freak** [comment]
@Friis1978 I am glad it is finally all good and working :)

**Comment by kesha-antonov** [comment]
Same here. 
```'FirebaseCore/FirebaseCore.h' file not found``` when doing Archive

**Comment by wanbok** [comment]
@NirpE Sorry for a late response. Everything that I used, works normally. But I use it with just a few functions.

**Comment by jamesreilly5** [comment]
Same problem for me, the only workaround that worked was downgrading to 4.1.0 😞

**Comment by mbbender** [comment]
I solved this problem by upgrading my packages. RN 0.56, RNF 5.0-rc1, pod Firebase/Core 5.6

**Comment by phuongwd** [comment]
same problem for me, issue RN 0.56, RNF 5.0-rc1, pod Firebase/Core 5.6

**Comment by AdriaRios** [comment]
Any oficial solution for this issue?

**Comment by abdullahceylan** [comment]
- Remove **Podfile.lock** file
- Remove ios/**Pods** folder
- Remove ios/**build** folder
- Remove Projectname.**xcworkspace** file
- Run `pod install`
- Rebuild.

It should be solved.

**Comment by SudoPlz** [comment]
@oferRounds I'm trying to figure the solution I should use on my end.

You see our project is an Objective-C project that requires a swift library (PromiseKit) - and not the opposite.

If I just remove `use_frameworks!` from our podfile, it won't build because libraries like `swiftCoreFoundation` will be missing.

What is the right way to remove `use_frameworks!` AND keep those swift pods working?

Here's my podfile:

```
platform :ios, '10.0'

target 'AcuityApp' do
    
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    
    pod 'PromiseKit', :modular_headers => true
    
    # react-native-firebase
    pod 'Firebase/Core', '~> 5.3.0'
    pod 'Firebase/DynamicLinks', '~> 5.3.0'
    pod 'Firebase/Messaging', '~> 5.3.0'
    
end

```

Thank you

**Comment by SudoPlz** [comment]
@oferRounds I have tried adding `:modular_headers => true ` next to `pod 'PromiseKit'` as you can see, but it still fails on build time, telling me that basic swift libraries like `swiftBasicContainer` was not found.

My cocoapods knowledge is not that great, but I did try that at least.
Is that not what I was supposed to do?

**Comment by oferRounds** [comment]
@SudoPlz can you check which Cocoa Pods version are you using? It should be at least 1.5.0

https://stackoverflow.com/questions/18931091/how-to-check-a-version-of-a-cocoapods-framework

**Comment by SudoPlz** [comment]
```
pod --version
1.5.3
```

**Comment by oferRounds** [comment]
Got you. And which Xcode version?

**Comment by SudoPlz** [comment]
Xcode 10.0

**Comment by oferRounds** [comment]
Got you... Then, sorry, for some reason this solution does not work for you. Not Sure what’s the reason. Obviously there is some issue with `react-native-firebase`, I hope it will be fixed soon..

**Comment by SudoPlz** [comment]
Cool, thanks for helping out on a Sunday man, I appreciate it.

**Comment by oferRounds** [comment]
Sure! :) Sorry I couldn’t solve it :\

**Comment by phips28** [comment]
I just removed the `use_frameworks!` from my Podfile.

**Comment by Jackyaung** [comment]
have been working this for more then three days, no matter how I tried, it just keep telling you , either Firebase not found or FirebaseCore/FirebaseCore.h not found.

**Comment by mikehardy** [comment]
I have just recently used the firebase starter with XCode 10.1/XCode10.2 (just came out) and it works.

I then carefully adapted what the starter did into my codebase (using RN0.59.1 even) and it works.

There are a million ways to mess up a build system but if it helps to know that the starter works so you have a template to look through, and that the current 5.x code works if you carefully pull the starter's style in, maybe you can move forward

**Comment by keshavkaul** [comment]
@chrisbianca I am getting this issue on a new RN project with latest 5.x RN Firebase version.

I created a new RN project v0.59.8, added react-native-firebase v5.3.1 and used the following pod file

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FirebaseReactNative' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FirebaseReactNative
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  
  pod 'Fabric'
  pod 'Crashlytics'

  target 'FirebaseReactNativeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
I get this error: 

```
/firebase-react-native/node_modules/react-native-firebase/ios/RNFirebase/analytics/RNFirebaseAnalytics.m:6:9: fatal error: 'FirebaseCore/FIRAnalyticsConfiguration.h' file not found
#import <FirebaseCore/FIRAnalyticsConfiguration.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by mackenziemance** [comment]
@keshavkaul I also ran in to this. Your pod version is ahead of what's currently supported. Lock your pods at 5.20.2, that should resolve the issue.

**Comment by keshavkaul** [comment]
@mackenziemance Oh, how silly of me. I had just upgraded to latest version of RN firebase and forgot to checkout the dependencies. Thanks!

**Comment by erez-guesty** [comment]
@mackenziemance 
if i use npm firebase 4.3.0
so which lock version should i use in the pod file?
also 5.20.2 ?
on which pods?

**Comment by mikehardy** [comment]
I have no experience with a 'firebase' package on npm, or the 4.3.0 version of react-native-firebase, but with react-native-firebase 5.3.1, the firebase-ios-sdk Pods 5.20.2 work

**Comment by MuhammadUsman786786** [comment]
I solve this issue:

1. delete the Pod folder
2. delete the Pod lock file
3. This is an important step: Specify the dependency version which was mentioned in `react-native-firebase `docs

**Comment by mapo80** [comment]
@MuhammadUsman786786 thanks very much, now it works! +1

**Comment by infiniteline** [comment]
@MuhammadUsman786786 +1 from me. It seems that locking the dependency versions works.

**Comment by belal-mazlom** [comment]
I get it work after apply @MuhammadUsman786786 solution
If you are working with version v5.+ of react-native-firebase you must apply this fix in Podfile:
```
pod 'Firebase/Core', '~> 5.20.1'
pod 'Firebase/Messaging', '~> 5.20.1'
```

**Comment by shrinandhini2801** [comment]
@belal-mazlom i did as you suggest but i got the below error 

ld: framework not found FirebaseCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Note : am using  "react-native-firebase": "5.4.2" and xcode 10.2.1

Please help

**Comment by shrinandhini2801** [comment]
@MuhammadUsman786786 is there any other that needs to be taken care of ? Like header search path ??

**Comment by belal-mazlom** [comment]
@shrinandhini2801 
Did you try these steps?
1- delete the Pod folder
2- delete the Pod lock file
3- run `pod update`

**Comment by shrinandhini2801** [comment]
@belal-mazlom yes i have tried those steps and removed the pod lock , pod folder , workspace and did the fresh pod install.. Did the steps for almost 5 to 6 times .. No luck

**Comment by shrinandhini2801** [comment]
@belal-mazlom Finally i got it running . Although the explicit mentioning of versions in pod file didn't work for me , i was able to successfully build and archive with latest versions of firebase (both in cocoapods and in package.json). None of the place , i have mentioned the version numbers . 

All i did was removed node modules ->  did fresh install -> did pod install (without mentioning version  but commented "use_frameworks!" -> clean and build. 

It worked like charm. One important point worth mentioning is , whenever i manullay change somethinh in header search path i ended up with an issue so i just left the `react-native link react-native-firebase `  to do the job and i didn't touch any of the default configs.

**Comment by mikehardy** [comment]
If you have not mentioned pod versions you will likely get the most recent ones (6.x.x) of the firebase ios sdk, and it won't work. Our compatibility chart clearly indicates that you must use 5.20.2 maximum. I demonstrate in the make-demo.sh script here https://github.com/mikehardy/rnfbdemo exactly how to go from scratch to a working react-native-firebase app, I would examine it to see how it works. It follows the docs with the exception of the Podfile, it has a workaround for a header file issue we are tracking here #2163

**Comment by artyom-developer** [comment]
Error :/ 617 duplicate symbols for architecture x86_64

**Comment by mikehardy** [comment]
This issue has been closed more than a year, it is attracting unfocused reports now and not generating helpful discussion. Please open new issues following the issue template if you are experiencing problems
