### ISSUE TITLE
5.0.0-rc1 - Notification.js problem

### ISSUE THREAD

**Issue by NichAga** [invertase/react-native-firebase#1445]
### Issue

Hi,
I'm having some crashes when there's a notification coming in, using your latest 5.0 package. It's an undefined when getting a native module while testing it on Android.
So I went into Notification.js and modified it a bit:

Initial code:
```
constructor(nativeNotification, notifications) {
    if (nativeNotification) {
      this._body = nativeNotification.body;
      this._data = nativeNotification.data;
      this._notificationId = nativeNotification.notificationId;
      this._sound = nativeNotification.sound;
      this._subtitle = nativeNotification.subtitle;
      this._title = nativeNotification.title;
    }

      this._ios = new IOSNotification(this, notifications, nativeNotification && nativeNotification.ios); // Defaults
      this._android = new AndroidNotification(this, nativeNotification && nativeNotification.android);

    this._data = this._data || {}; // TODO: Is this the best way to generate an ID?

    this._notificationId = this._notificationId || generatePushID();
  }
```

Code with the check for the Platform I put in:
```
constructor(nativeNotification, notifications) {
    if (nativeNotification) {
      this._body = nativeNotification.body;
      this._data = nativeNotification.data;
      this._notificationId = nativeNotification.notificationId;
      this._sound = nativeNotification.sound;
      this._subtitle = nativeNotification.subtitle;
      this._title = nativeNotification.title;
    }

    if(Platform.OS === 'ios'){
      this._ios = new IOSNotification(this, notifications, nativeNotification && nativeNotification.ios); // Defaults
    }else{
      this._android = new AndroidNotification(this, nativeNotification && nativeNotification.android);
    }

    this._data = this._data || {}; // TODO: Is this the best way to generate an ID?

    this._notificationId = this._notificationId || generatePushID();
  }
```

Now, on Android, it doesn't crash anymore. Should it be like mine, or it shouldn't crash anyway?

### Environment

1. Application Target Platform: Both, but tested only on Android

2. Development Operating System: macOS HIgh Sierra

4. `React Native` version: 0.57 rc3

5. `React Native Firebase` Version: 5.0.0-rc1

6. `Firebase` Module: notifications

7. Are you using `typescript`? no

---

Loving `react-native-firebase`? Please consider supporting them with any of the below:

* 👉 Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)
* 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
* 👉 Star this repo on GitHub ⭐️

**Comment by Salakar** [comment]
Hey @NichAga 

There's an issue at the moment like you've found, see: https://github.com/invertase/react-native-firebase/pull/1393#issuecomment-416523878

The workaround is the following:

![image](https://user-images.githubusercontent.com/5347038/44915532-173ef100-ad2b-11e8-9f99-fc22078d70a5.png)

**Comment by NichAga** [comment]
Hi, @Salakar 
I think I'm going to stay with my modification, because has been working good, both in iOS and Android.

**Comment by Salakar** [comment]
Hey, rc2 is up, please could you try it out, this should be resolved in there now. Thanks

**Comment by rahulgi** [comment]
@Salakar, I am still experiencing this issue on Android on 5.0.0-rc2.

**Comment by kkotelczuk** [comment]
I got this issue with `React Native: 0.57` and `react-native-firebase: 5.0.0-rc2`.

**Comment by Salakar** [comment]
@rahulgi this bug was introduced by an external PR, specifically: https://github.com/invertase/react-native-firebase/pull/1393. As I didn't originally write the PR and the author is currently AWOL it's difficult for me to pin-point the exact issue without proper stack traces or a reproducable repo.

After debugging with someone on discord it appeared that my change had resolved the issue, but my guess after your feedback is that this is not the case. 😞 

If you or anyone could assist me with a stack trace and perhaps using the debugger and have `pause on uncaught exception` etc showing me the stack there and the line it breaks on (code view) as well as the native notification payload/scope variables etc that'd be really helpful.


I can push another RC pretty quick once we can resolve this

**Comment by rahulgi** [comment]
@Salakar, happy to help, and thanks for the quick reply! Tried to do the things you asked for below, and let me know if there's any further information you want. Going to sleep now, but I can look further in the morning / maybe dig through that PR you referenced. Cheers!

**Screencap of source at caught exception:**
<img width="1680" alt="screen shot 2018-09-20 at 12 32 16 am" src="https://user-images.githubusercontent.com/2237985/45764052-ca38a580-bc6c-11e8-95cb-3d177e27e77e.png">

**Stack trace at exception:**
```
> console.trace()
VM171:1 console.trace
(anonymous) @ VM171:1
complete @ IOSNotification.js:28
IOSNotification @ IOSNotification.js:39
Notification @ Notification.js:31
(anonymous) @ index.js:65
emit @ EventEmitter.js:190
(anonymous) @ events.js:40
emit @ EventEmitter.js:190
__callFunction @ MessageQueue.js:344
(anonymous) @ MessageQueue.js:107
__guard @ MessageQueue.js:291
callFunctionReturnFlushedQueue @ MessageQueue.js:106
(anonymous) @ debuggerWorker.js:72
```

**nativeNotification payload:**
Not sure if there's a better way to do this / this is what you want, but I added a `console.log` to print out the `nativeNotification` variable in the JS at line 26 of `Notification.js`.

```
nativeNotification {
  "android": {},
  "title": "RNFirebase 5.0.0-rc2 bug demo",
  "notificationId": "0:1537371442806982%6add9f926add9f92",
  "data": {},
  "body": "Hi!"
}
```

**Comment by Salakar** [comment]
@rahulgi awesome thanks for that, straight away I can see the issue 👌 will get a new rc out.

**Comment by rahulgi** [comment]
@Salakar, much appreciated!

**Comment by Salakar** [comment]
@rahulgi @kkotelczuk @JanErikFoss @NichAga RC3 has just been published, please give it a go and let me know how it goes.

Thanks again @rahulgi for the assist 👍

**Comment by NichAga** [comment]
@Salakar gonna test it right now, thanks!

**Comment by Salakar** [comment]
@NichAga thanks for testing :) 

Will close this issue now. 🎉

**Comment by rahulgi** [comment]
@Salakar, ditto, worked great! Thanks for the callout in the commit message too lol ^.^ feeling very honored for not doing much.

**Comment by JanErikFoss** [comment]
@leethree Try removing the quickfix, just use

`new firebase.notifications.Notification()`

**Comment by huyhai** [comment]
same at  "react-native-firebase": "^5.0.0-rc4"
key cannot be nil' was thrown while invoking complete on target RNFirebaseNotifications with params (
    "<null>",
    1
)

**Comment by Salakar** [comment]
Use notifications as normal now on the full v5.0.0 release as per the docs. The `'quick fix'` is no longer required

**Comment by pepincho** [comment]
Hello guys,
I am having the same problem on iOS with
```
"react": "16.5.0",
"react-native": "0.57.1",
"react-native-firebase": "^5.0.0",
```
![screen shot 2018-10-05 at 4 07 44 pm](https://user-images.githubusercontent.com/4939913/46537105-23cde080-c8b9-11e8-8d7b-57dbf02ac6e2.png)

Could anyone help me?
