### ISSUE TITLE
Dynamic Links - createShortDynamicLink not working on Android

### ISSUE THREAD

**Issue by jeremywen3** [invertase/react-native-firebase#1554]
### Issue

**Reference:**
https://rnfirebase.io/docs/v5.x.x/links/reference/links

I'm am trying to generate a short dynamic link see code below:

```
 firebase.links().createShortDynamicLink(dynamicLink, 'UNGUESSABLE')
     .then((url) => {
         console.log(url);
      })
      .catch((error) => {
          console.log(error);
      });
```
This is working fine on iOS but on Android I'm getting this error:

Error: 8: 
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:397)
    at MessageQueue.js:127
    at MessageQueue.__guard (MessageQueue.js:297)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:126)
    at t (RNDebuggerWorker.js:1)

**Relevant gradle dependencies:**
```
implementation "com.google.firebase:firebase-core:16.0.3"
implementation "com.google.firebase:firebase-invites:16.0.3"
```
Funnily enough _createDynamicLink(dynamicLink)_ works fine on both platforms.

### Environment

1. Application Target Platform:

Android

2. Development Operating System:

macOS Sierra

3. Build Tools:

Android SDK version 27

4. `React Native` version:

0.57.0

5. `React Native Firebase` Version:

5.0.0

6. `Firebase` Module:

Dynamic Links

7. Are you using `typescript`?

no

**Comment by nabylb** [comment]
I have the exact same error.

```
implementation "com.google.firebase:firebase-core:16.0.4"
implementation "com.google.firebase:firebase-invites:16.0.4"
```

```
Error: 8: 
    at createErrorFromErrorData (NativeModules.js:146)
    at NativeModules.js:95
    at MessageQueue.__invokeCallback (MessageQueue.js:392)
    at MessageQueue.js:128
    at MessageQueue.__guard (MessageQueue.js:291)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:127)
    at t (RNDebuggerWorker.js:1)
```

**Comment by mfharding1** [comment]
I am having the same issue.

**Comment by mfharding1** [comment]
Hi @jeremywen3 and @nabylb I found out the issue. The current version of firebase-dynamic -links is broken for generating short links. This is causing an error to throw that is unhandled by firebase and presents in a lot of weird ways. I found that be downgrading my firebase versions to 16.0.1 it fixed these issue. Here is my modified app/build.gradle: 

```
    compile 'com.google.firebase:firebase-core:16.0.1'
    compile 'com.google.firebase:firebase-storage:16.0.1'
    compile 'com.google.firebase:firebase-auth:16.0.1'
    compile 'com.google.firebase:firebase-messaging:17.3.3'
    compile 'com.google.firebase:firebase-invites:16.0.1'
    compile 'com.google.firebase:firebase-dynamic-links:16.0.1'
```

**Comment by jcsena** [comment]
I am having the same issue.

**Comment by jcsena** [comment]
I fixed this with a workaround 
```
POST https://firebasedynamiclinks.googleapis.com/v1/shortLinks?key=**{api_key}**
Content-Type: application/json

{
   "longDynamicLink": "https://example.page.link/?link=http://www.example.com/&apn=com.example.android&ibi=com.example.ios",
   "suffix": {
     "option": "UNGUESSABLE"
   }
}
```

**Comment by jeremywen3** [comment]
Seems appears that Firebase have fixed it. createShortDynamicLink is working on 16.0.3

**Comment by Salakar** [comment]
The latest release requires 16.0.3+ and above so I'd consider this resolved now.

**Comment by ggdegreat** [comment]
i am using the latest release

implementation "com.google.firebase:firebase-invites:16.0.4"
implementation "com.google.firebase:firebase-dynamic-links:16.1.2"

but still didn't work. Error still occured:

 at createErrorFromErrorData (NativeModules.js:146)

**Comment by bilalsyed001** [comment]
upgrading to 16.0.6 fixes issue for me. Good luck!
