### ISSUE TITLE
Archiving issues iOS => FirebaseCore/FirebaseCore.h' file not found -- only on iOS Release config

### ISSUE THREAD

**Issue by Benjuari** [invertase/react-native-firebase#1764]
As issues revolving around archiving keep getting closed i want to open a new thread.

i refer to some issues: one of them was :https://github.com/invertase/react-native-firebase/issues/1166

There has been a solution found for this problem. 

"Add the correct archive header path to the Release part of both Framework Search Paths and Header Search Paths in the RNFirebase project build settings. This defaults to "$(BUILD_ROOT)/../IntermediateBuildFilesPath/UninstalledProducts/iphoneos" but the location is dependent on your overall project build settings."

This works locally but not if you are working with a remote CI/CD process.

Can you guys please update this to make it work with a remote build process.

Using modular headers in podfile does not work nor can we remove use_frameworks as we use different pods which rely on this

**Comment by bartolkaruza** [comment]
The workaround mentioned at the [3.2.2 release notes](https://github.com/invertase/react-native-firebase/releases/tag/v3.2.2) does not work for my project. The problem persists even after adding the Pods framework to the RNFirebase project build phase.

Here is the work around that I use now, in the project Podfile, that works reliably on clean checkout without dependency modifications;

```
post_install do |installer|
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end
```

**Comment by Ehesp** [comment]
Please follow the issue template @Benjuari - we have no clue what version you're working with here.

**Comment by bartolkaruza** [comment]
@Ehesp I can confirm this issue is relevant on 5.2.0 (latest at the time of writing). Could you please re-open this?

**Comment by Benjuari** [comment]
@bartolkaruza thanks for the support! 
@Ehesp I also confirm this! I was working with the latest version.

**Comment by sadafk831** [comment]
I was having the same issue on react-native 0.58
The Post install script worked for me  👍 
I added the script in the post_install script

**Comment by keshavkaul** [comment]
> The workaround mentioned at the [3.2.2 release notes](https://github.com/invertase/react-native-firebase/releases/tag/v3.2.2) does not work for my project. The problem persists even after adding the Pods framework to the RNFirebase project build phase.
> 
> Here is the work around that I use now, in the project Podfile, that works reliably on clean checkout without dependency modifications;
> 
> ```
> post_install do |installer|
>   system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
> end
> ```

@bartolkaruza This works when Archiving but on running on device, I get the Missing Module Error:
in `native.js` file inside `initialiseNativeModule` function.

I'm simply trying to listen for Auth change event.

**Comment by keshavkaul** [comment]
@bartolkaruza @Ehesp Any help would be greatly appreciated!

**Comment by ahsanmster** [comment]
any update, and i don't even have pod file in my project.

<img width="402" alt="Screenshot 2019-04-10 at 5 11 28 PM" src="https://user-images.githubusercontent.com/32548815/55877581-d3ab4000-5bb3-11e9-94d6-c5f4e0c5f05f.png">

**Comment by AndreyPatseiko** [comment]
Problem the still exist.

**Comment by mikehardy** [comment]
#2163 is the canonical place we are tracking header file problems, and it has a workaround (actually the one listed above - a header copy as Podfile post install step) that works in archive for release mode, including with a reproducible demo that proves it

**Comment by Sarathphd** [comment]
Hi, I am also face this issue. But I have fixed error. First goto project folder in ios folder and open profile file you just Commit use_framework. Then delete projectName.xcworkspace, pod folders and profile.lock file. And pod update, pod install finally open project to xcode and build. Easy to solve this issue and fixed.

**Comment by taniksha-mfy** [comment]
I have tried everything but still facing the same issue. someone please help
