### ISSUE TITLE
🔥 library not found for -lRNFirebase

### ISSUE THREAD

**Issue by danielmartinprieto** [invertase/react-native-firebase#1978]
## Issue

I can't get Firebase Analytics on iOS working because the project doesn't compile. I get this error: `library not found for -lRNFirebase`.

Some notes:
- I have a background as an iOS developer, so I'm familiar with both Cocoapods and Xcode.
- I've followed the installation guide for iOS step by step, I understand it and I don't see anything wrong there.
- I've installed `Firebase/Core` via Cocoapods and before integrating `react-native-firebase`, the app was compiling and I could see my project in the Firebase dashboard.
- I'm **not** using Cocoapods to integrate the react native library.
- I've used `react-native link react-native-firebase` and the changes applied to my Xcode project makes sense, basically it has added both `RNFirebase.xcodeproj` and `libRNFirebase.a` to my project.
- I get the same error both compiling using Xcode and vía `react-native run-ios`.
- Unrelated, but I got it working on Android without any problem.

It seems `libRNFirebase.a` can't be built because it doesn't detect the libraries installed via Cocoapods.

---

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

I'm using Cocoapods only for Firebase/Core and this is properly working. The compilation problem appears when I link the React Native library via `react-native link`.

#### `AppDelegate.m`:

```objc
// N/A
```

---

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

---

## Environment

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **If known, the version of the platform are you experiencing the issue on:**
  - iOS 12
- **Operating System:**
  - [x] MacOS, version: `Mojave`
  - [ ] Windows, version: `N/A`
  - [ ] Other, please specify: `N/A`
- **Build Tools:**
  - Xcode 10
- **`React Native` version:**
  - 58
- **`React Native Firebase` library version:**
  - 5.2.3
- **`Firebase` module(s) you're using that has the issue:**
  - [ ] **N/A**
  - [ ] Authentication
  - [x] Analytics
  - [ ] Cloud **Firestore**
  - [ ] Cloud **Messaging** (FCM)
  - [ ] Crashlytics
  - [ ] Dynamic **Links**
  - [ ] **Functions** Callable
  - [ ] In App Messaging
  - [ ] Indexing
  - [ ] Invites
  - [ ] Instance ID
  - [ ] ML Kit
  - [ ] Notifications
  - [ ] Performance Monitoring
  - [ ] Realtime **Database**
  - [ ] Remote **Config**
  - [ ] Storage
- **Are you using `TypeScript`?**
  - [x] No
  - [ ] Yes, version: `N/A`
- **Are you using Expo, e.g. `ExpoKit`?**
  - [x] No
  - [ ] Yes, I've _not_ ejected
  - [ ] Yes, but I **have** ejected to `ExpoKit`
  - [ ] Yes, but I **have** ejected to vanilla React Native
  - Expo version: `N/A`

---

Think `react-native-firebase` is great? Please consider supporting the project with any of the below:

- 👉 Donate via [Open Collective](https://opencollective.com/react-native-firebase/donate)
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter
- 👉 Star this repo on GitHub ⭐️
- 👉 Contribute; see our [contributing guide](./../../CONTRIBUTING.md)

**Comment by aryalprakash** [comment]
@danielmartinprieto I'm also getting this error. Did you find any solution?

**Comment by danielmartinprieto** [comment]
No, sorry, @aryalprakash. I’m waiting for the maintainers to give some clues, maybe they know what’s going on here.

**Comment by aryalprakash** [comment]
@danielmartinprieto I removed `react-native-firebse` from node_modules and reinstalled package. Then the error is gone. I don't know why though.

**Comment by danielmartinprieto** [comment]
Just removing `react-native-firebase` from `node_modules` and run `npm install` again doesn't work for me.

@aryalprakash apart from removing the library from `node_modules`, have you unlinked it as well?

**Comment by dentemm** [comment]
I am having the same problem, nothing I have tried so far works

**Comment by danielmartinprieto** [comment]
It seems there are more people with the same problem: https://stackoverflow.com/questions/53617257/library-not-found-for-lrnfirebase-react-native

**Comment by lunatolun** [comment]
I had the exact same error and I noticed something. in xCode, under Pods > Pods, the libraries were invisible. I went and checked if they were actually there, and yes, they were. I restarted XCode and the folders were there this time, and stopped giving the error. Weird...

**Comment by famu1hundred** [comment]
I was able to resolve this by restarting XCode, deleting my node_modules folder and running yarn (or npm install). Clean and Build...error gone

**Comment by danielmartinprieto** [comment]
I think these two last comment weren't the same problem, as I'm not even using Xcode to compile the project, but react-native cli. Also, I can reproduce it in my CI setup, where things are not cached.

**Comment by danielmartinprieto** [comment]
Oh 😢

**Comment by mikehardy** [comment]
FWIW I have this working well in Android and iOS, so know that it is possible. Also worth mentioning that I had to do a search through my linking search paths and make sure they were correct, during install. There were some entries duplicated, recursion where it shouldn't be etc. You mention you are experienced with pods + xcode, so if you hunt down your linker paths and make sure they are perfect this should work. You may also look at the react-native-firebase starter project and see how it works, as it will work out of the box

**Comment by danielmartinprieto** [comment]
Thanks, @mikehardy.

Could you please share your search paths configuration to see if we're doing something wrong? We have integrated some other native libraries like this and they all work, so I'm wondering if there is something in particular I should pay attention to integrating this library's bridge in an iOS app.

I will also take a look at the Xcode's config of the react-native-firebase starter project to see if I can find something.

**Comment by mikehardy** [comment]
bulid settings -> other linker flags -> 2 entries, `$(inherited)` and `-lc++`

I don't think there is anything else going on for my project, but I recall that it was a mess before I stripped it down to that and put the inherited in there. I am actually pretty novice at XCode/iOS so if there is a better way to get that info I won't know. Perhaps there is a chunk of raw plist or project file that is good

**Comment by danielmartinprieto** [comment]
I've confirmed I have those as well. There must be something else (or something missing) in my project  and I get that error.

**Comment by emkou** [comment]
Do you have any other build configurations apart from Develop and Release ?

**Comment by testshallpasswork** [comment]
I'm able to reproduce on App Center CI but not on development machine. I am a bit perplexed.

**Comment by mikehardy** [comment]
Creation of functioning (archivable) react-native-firebase app, from init to running: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh

**Comment by mikehardy** [comment]
As I was scanning through this might be the best place to focus for that #1667 @testshallpasswork

**Comment by mt11i** [comment]
in my case when i try to build in xcode it's giving me above error 
i have fixed this issue by doing  following steps
  1. npm install
  2. go to ios dir 
  3. pod install
  4. go back to project root dir and run react-native link

**Comment by 2n2n** [comment]
Oh boy, I fixed this because I selected the wrong file to open. 
1. close xcode
2. open another project..
3. select `ios/myproject.xcworkspace` not myproject.xcodeproj
4. build and run

**Comment by mohshbool** [comment]
> Oh boy, I fixed this because I selected the wrong file to open.
> 
> 1. close xcode
> 2. open another project..
> 3. select `ios/myproject.xcworkspace` not myproject.xcodeproj
> 4. open terminal targeting to the root of your project folder and run `rm -rf ./node_module && npm install` (you can also use yarn by replacing npm install.)
> 5. `react-native link`
> 6. build and run

that didn't solve my problem. using `react-native: 0.59.9` and `react-native-firebase: 5.5.3` with pod `'Firebase/Core', '~> 6.3.0'`

**Comment by mikehardy** [comment]
Check mikehardy/rnfbdemo repo on github. Make-demo-rrn59.sh script shows how to make it work

**Comment by moahammadalt** [comment]
any update on this issue, this library is full of bugs and problem,it ruined my life, i wish there is a dislike in Github

**Comment by mikehardy** [comment]
@moahammadalt that is insulting and off topic. There are numerous examples on github of how to make things work. Keep it civil.

**Comment by mikehardy** [comment]
This is clearly attracting low-quality comments. My comment above for RN59 contains the canonical example of how to integrate react-native-firebase with a react-native 0.59 project, which was the original bug. Should you need to, there's a script in that repo that does the same for RN60. Follow those steps exactly and it works.
