### ISSUE TITLE
onSnapshot for CollectionReference doesn't match official API's - doesn't check for .next()

### ISSUE THREAD

**Issue by reimertz** [invertase/react-native-firebase#2066]
Sorry for removing the entire template but it should be fairly obvious what the issue is. 

Was trying to integrate [RxFire](https://github.com/firebase/firebase-js-sdk/blob/master/packages/rxfire/) and hit a brick wall. Finally realized that RNF is not handling the observer the same way official API's do. 😅 

Just like we currently do for a **DocumentReference**, we check if an passed observer contains next etc: https://github.com/invertase/react-native-firebase/blob/v5.x.x/src/modules/firestore/DocumentReference.js#L132

But if we look at **CollectionReference**, we don't follow the the same API: https://github.com/invertase/react-native-firebase/blob/v5.x.x/src/modules/firestore/CollectionReference.js#L85

For reference, here is **firebase-ios-sdk implementation:** https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/api/database.ts#L988

I might be missing something but this bug seem to to cause RxFire to fail on React Native if you use Firestore. 

I would be up to help out here, just want to be sure it's a legit bug and not me having a bug in my brain. :D

**Comment by Salakar** [comment]
Hey @reimertz - sorry for the delay on responding to this - if there's a discrepancy I'll get it addressed in v6 Firestore - I think the links you provided might be stale now as they don't seem to match up so can't quite confirm 😅

**Comment by Salakar** [comment]
Hey @reimertz,

A pre-release v6 release of firestore is up now with this fixed and many other Web SDK discrepancies fixed (full re-write with full tests coverage) - [[changelog]](https://github.com/invertase/react-native-firebase/blob/master/CHANGELOG.md#cloud-firestore-firestore)

**Comment by alfonsodev** [comment]
I'm not able to integrate RxFire with Firestore and RNFirebase
just the basic 
```
doc(firestore.doc("myCollection/Id7NiY1ASequaN24XFGf")).subscribe(snapshot => {
  console.log(snapshot.data());
});
```
doesn't trigger the subscribe 
@reimertz did you try on v6 ?
could we re-open this issue if still doesn't work on v6 ?
thanks !

**Comment by reimertz** [comment]
Sorry for the delay in answering @alfonsodev. I ended up writing small react hooks myself combining rxjs and react-native-firebase so cannot confirm nor deny if I see the same issues myself.

**Comment by jluxenberg** [comment]
I can confirm this is still an issue on the latest version of @react-native-firebase/*. I'm on a combination of v7 and v8 (latest as of this writing):
```
jareds-mbp:app jared$ grep '^"@react-native-firebase/' yarn.lock
"@react-native-firebase/app-types@6.7.2":
"@react-native-firebase/app@^7.2.0":
"@react-native-firebase/auth@^8.0.4":
"@react-native-firebase/firestore@^7.1.5":
"@react-native-firebase/storage@^7.1.3":
```

**Comment by zhigang1992** [comment]
Yeap, it's happening on for `auth.onAuthStateChanged` as well.

**Comment by zhigang1992** [comment]
I can confirm that react-native-firebase works with `onSnapshot({next: ..., error: ...})`

however, the firebase-js-sdk is doing something else 

https://github.com/firebase/firebase-js-sdk/blob/5b87b5911b29a0af5962fda05d9bbadb0d47a789/packages/rxfire/firestore/fromRef.ts#L28

https://github.com/firebase/firebase-js-sdk/blob/39ca8ecf940472159d0bc58212f34a70146da60c/packages/firestore-types/index.d.ts#L233-L240

It's passing option as first argument and subscriber as seconds.

Which isn't supported by react-native-firebase.
