### ISSUE TITLE
GoogleUtilites pod 6.7.0 / firebase-ios-sdk 6.28.0 incompatibility (was 'GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h' file not found)

### ISSUE THREAD

**Issue by croossin** [invertase/react-native-firebase#3938]
## Issue

Issues when trying to use `react-native-firebase/auth`

When trying to run, I see an error as follows:
```
'GoogleUtilities/AppDelegateSwizzler/Private/GULApplication.h' file not found
```

<img width="266" alt="Screen Shot 2020-07-14 at 4 35 25 PM" src="https://user-images.githubusercontent.com/7241069/87486368-07171e80-c5f0-11ea-9a10-409d219c3755.png">

---

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

def add_flipper_pods!(versions = {})
  versions['Flipper'] ||= '~> 0.33.1'
  versions['DoubleConversion'] ||= '1.1.7'
  versions['Flipper-Folly'] ||= '~> 2.1'
  versions['Flipper-Glog'] ||= '0.3.6'
  versions['Flipper-PeerTalk'] ||= '~> 0.0.4'
  versions['Flipper-RSocket'] ||= '~> 1.0'

  pod 'FlipperKit', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/SKIOSNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitUserDefaultsPlugin', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitReactPlugin', versions['Flipper'], :configuration => 'Debug'

  # List all transitive dependencies for FlipperKit pods
  # to avoid them being linked in Release builds
  pod 'Flipper', versions['Flipper'], :configuration => 'Debug'
  pod 'Flipper-DoubleConversion', versions['DoubleConversion'], :configuration => 'Debug'
  pod 'Flipper-Folly', versions['Flipper-Folly'], :configuration => 'Debug'
  pod 'Flipper-Glog', versions['Flipper-Glog'], :configuration => 'Debug'
  pod 'Flipper-PeerTalk', versions['Flipper-PeerTalk'], :configuration => 'Debug'
  pod 'Flipper-RSocket', versions['Flipper-RSocket'], :configuration => 'Debug'
  pod 'FlipperKit/Core', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/CppBridge', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBCxxFollyDynamicConvert', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FBDefines', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FKPortForwarding', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitHighlightOverlay', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitLayoutTextSearchable', versions['Flipper'], :configuration => 'Debug'
  pod 'FlipperKit/FlipperKitNetworkPlugin', versions['Flipper'], :configuration => 'Debug'
end

# Post Install processing for Flipper
def flipper_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'YogaKit'
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.1'
      end
    end
  end
end

target 'APP_NAME' do
  # Pods for APP_NAME
  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'

  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/callinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

#   pod 'lottie-ios', :path => '../node_modules/lottie-ios'
# pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

  target 'APP_NAMETests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  add_flipper_pods!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'APP_NAME-tvOS' do
  # Pods for APP_NAME-tvOS

  target 'APP_NAME-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

```

#### `ios/Podfile.lock`:

```ruby
PODS:
  - boost-for-react-native (1.63.0)
  - CocoaAsyncSocket (7.6.4)
  - CocoaLibEvent (1.0.0)
  - DoubleConversion (1.1.6)
  - FBLazyVector (0.62.2)
  - FBReactNativeSpec (0.62.2):
    - Folly (= 2018.10.22.00)
    - RCTRequired (= 0.62.2)
    - RCTTypeSafety (= 0.62.2)
    - React-Core (= 0.62.2)
    - React-jsi (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - Firebase/Auth (6.27.1):
    - Firebase/CoreOnly
    - FirebaseAuth (~> 6.6.0)
  - Firebase/CoreOnly (6.27.1):
    - FirebaseCore (= 6.8.1)
  - FirebaseAuth (6.6.0):
    - FirebaseCore (~> 6.8)
    - GoogleUtilities/AppDelegateSwizzler (~> 6.5)
    - GoogleUtilities/Environment (~> 6.5)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseCore (6.8.1):
    - FirebaseCoreDiagnostics (~> 1.3)
    - GoogleUtilities/Environment (~> 6.5)
    - GoogleUtilities/Logger (~> 6.5)
  - FirebaseCoreDiagnostics (1.5.0):
    - GoogleDataTransport (~> 7.0)
    - GoogleUtilities/Environment (~> 6.7)
    - GoogleUtilities/Logger (~> 6.7)
    - nanopb (~> 1.30905.0)
  - Flipper (0.33.1):
    - Flipper-Folly (~> 2.1)
    - Flipper-RSocket (~> 1.0)
  - Flipper-DoubleConversion (1.1.7)
  - Flipper-Folly (2.2.0):
    - boost-for-react-native
    - CocoaLibEvent (~> 1.0)
    - Flipper-DoubleConversion
    - Flipper-Glog
    - OpenSSL-Universal (= 1.0.2.19)
  - Flipper-Glog (0.3.6)
  - Flipper-PeerTalk (0.0.4)
  - Flipper-RSocket (1.1.0):
    - Flipper-Folly (~> 2.2)
  - FlipperKit (0.33.1):
    - FlipperKit/Core (= 0.33.1)
  - FlipperKit/Core (0.33.1):
    - Flipper (~> 0.33.1)
    - FlipperKit/CppBridge
    - FlipperKit/FBCxxFollyDynamicConvert
    - FlipperKit/FBDefines
    - FlipperKit/FKPortForwarding
  - FlipperKit/CppBridge (0.33.1):
    - Flipper (~> 0.33.1)
  - FlipperKit/FBCxxFollyDynamicConvert (0.33.1):
    - Flipper-Folly (~> 2.1)
  - FlipperKit/FBDefines (0.33.1)
  - FlipperKit/FKPortForwarding (0.33.1):
    - CocoaAsyncSocket (~> 7.6)
    - Flipper-PeerTalk (~> 0.0.4)
  - FlipperKit/FlipperKitHighlightOverlay (0.33.1)
  - FlipperKit/FlipperKitLayoutPlugin (0.33.1):
    - FlipperKit/Core
    - FlipperKit/FlipperKitHighlightOverlay
    - FlipperKit/FlipperKitLayoutTextSearchable
    - YogaKit (~> 1.18)
  - FlipperKit/FlipperKitLayoutTextSearchable (0.33.1)
  - FlipperKit/FlipperKitNetworkPlugin (0.33.1):
    - FlipperKit/Core
  - FlipperKit/FlipperKitReactPlugin (0.33.1):
    - FlipperKit/Core
  - FlipperKit/FlipperKitUserDefaultsPlugin (0.33.1):
    - FlipperKit/Core
  - FlipperKit/SKIOSNetworkPlugin (0.33.1):
    - FlipperKit/Core
    - FlipperKit/FlipperKitNetworkPlugin
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - Folly/Default (= 2018.10.22.00)
    - glog
  - Folly/Default (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - GoogleDataTransport (7.0.0):
    - nanopb (~> 1.30905.0)
  - GoogleUtilities/AppDelegateSwizzler (6.7.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (6.7.0):
    - PromisesObjC (~> 1.2)
  - GoogleUtilities/Logger (6.7.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/Network (6.7.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (6.7.0)"
  - GoogleUtilities/Reachability (6.7.0):
    - GoogleUtilities/Logger
  - GTMSessionFetcher/Core (1.4.0)
  - lottie-ios (3.1.3)
  - lottie-react-native (3.4.0):
    - lottie-ios (~> 3.1.3)
    - React
  - nanopb (1.30905.0):
    - nanopb/decode (= 1.30905.0)
    - nanopb/encode (= 1.30905.0)
  - nanopb/decode (1.30905.0)
  - nanopb/encode (1.30905.0)
  - OpenSSL-Universal (1.0.2.19):
    - OpenSSL-Universal/Static (= 1.0.2.19)
  - OpenSSL-Universal/Static (1.0.2.19)
  - PromisesObjC (1.2.9)
  - RCTRequired (0.62.2)
  - RCTTypeSafety (0.62.2):
    - FBLazyVector (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTRequired (= 0.62.2)
    - React-Core (= 0.62.2)
  - React (0.62.2):
    - React-Core (= 0.62.2)
    - React-Core/DevSupport (= 0.62.2)
    - React-Core/RCTWebSocket (= 0.62.2)
    - React-RCTActionSheet (= 0.62.2)
    - React-RCTAnimation (= 0.62.2)
    - React-RCTBlob (= 0.62.2)
    - React-RCTImage (= 0.62.2)
    - React-RCTLinking (= 0.62.2)
    - React-RCTNetwork (= 0.62.2)
    - React-RCTSettings (= 0.62.2)
    - React-RCTText (= 0.62.2)
    - React-RCTVibration (= 0.62.2)
  - React-Core (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default (= 0.62.2)
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/CoreModulesHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/Default (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/DevSupport (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default (= 0.62.2)
    - React-Core/RCTWebSocket (= 0.62.2)
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - React-jsinspector (= 0.62.2)
    - Yoga
  - React-Core/RCTActionSheetHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTAnimationHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTBlobHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTImageHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTLinkingHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTNetworkHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTSettingsHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTTextHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTVibrationHeaders (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-Core/RCTWebSocket (0.62.2):
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core/Default (= 0.62.2)
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-jsiexecutor (= 0.62.2)
    - Yoga
  - React-CoreModules (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTTypeSafety (= 0.62.2)
    - React-Core/CoreModulesHeaders (= 0.62.2)
    - React-RCTImage (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-cxxreact (0.62.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsinspector (= 0.62.2)
  - React-jsi (0.62.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsi/Default (= 0.62.2)
  - React-jsi/Default (0.62.2):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React-jsiexecutor (0.62.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
  - React-jsinspector (0.62.2)
  - react-native-safe-area-context (0.7.3):
    - React
  - React-RCTActionSheet (0.62.2):
    - React-Core/RCTActionSheetHeaders (= 0.62.2)
  - React-RCTAnimation (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTTypeSafety (= 0.62.2)
    - React-Core/RCTAnimationHeaders (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTBlob (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - React-Core/RCTBlobHeaders (= 0.62.2)
    - React-Core/RCTWebSocket (= 0.62.2)
    - React-jsi (= 0.62.2)
    - React-RCTNetwork (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTImage (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTTypeSafety (= 0.62.2)
    - React-Core/RCTImageHeaders (= 0.62.2)
    - React-RCTNetwork (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTLinking (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - React-Core/RCTLinkingHeaders (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTNetwork (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTTypeSafety (= 0.62.2)
    - React-Core/RCTNetworkHeaders (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTSettings (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - RCTTypeSafety (= 0.62.2)
    - React-Core/RCTSettingsHeaders (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - React-RCTText (0.62.2):
    - React-Core/RCTTextHeaders (= 0.62.2)
  - React-RCTVibration (0.62.2):
    - FBReactNativeSpec (= 0.62.2)
    - Folly (= 2018.10.22.00)
    - React-Core/RCTVibrationHeaders (= 0.62.2)
    - ReactCommon/turbomodule/core (= 0.62.2)
  - ReactCommon/callinvoker (0.62.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-cxxreact (= 0.62.2)
  - ReactCommon/turbomodule/core (0.62.2):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-Core (= 0.62.2)
    - React-cxxreact (= 0.62.2)
    - React-jsi (= 0.62.2)
    - ReactCommon/callinvoker (= 0.62.2)
  - RNCMaskedView (0.1.10):
    - React
  - RNFBApp (8.2.0):
    - Firebase/CoreOnly (~> 6.27.0)
    - React
  - RNFBAuth (8.2.0):
    - Firebase/Auth (~> 6.27.0)
    - React
    - RNFBApp
  - RNGestureHandler (1.6.1):
    - React
  - RNReanimated (1.8.0):
    - React
  - RNScreens (2.7.0):
    - React
  - RNSVG (12.1.0):
    - React
  - Yoga (1.14.0)
  - YogaKit (1.18.1):
    - Yoga (~> 1.14)

DEPENDENCIES:
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - FBLazyVector (from `../node_modules/react-native/Libraries/FBLazyVector`)
  - FBReactNativeSpec (from `../node_modules/react-native/Libraries/FBReactNativeSpec`)
  - Flipper (~> 0.33.1)
  - Flipper-DoubleConversion (= 1.1.7)
  - Flipper-Folly (~> 2.1)
  - Flipper-Glog (= 0.3.6)
  - Flipper-PeerTalk (~> 0.0.4)
  - Flipper-RSocket (~> 1.0)
  - FlipperKit (~> 0.33.1)
  - FlipperKit/Core (~> 0.33.1)
  - FlipperKit/CppBridge (~> 0.33.1)
  - FlipperKit/FBCxxFollyDynamicConvert (~> 0.33.1)
  - FlipperKit/FBDefines (~> 0.33.1)
  - FlipperKit/FKPortForwarding (~> 0.33.1)
  - FlipperKit/FlipperKitHighlightOverlay (~> 0.33.1)
  - FlipperKit/FlipperKitLayoutPlugin (~> 0.33.1)
  - FlipperKit/FlipperKitLayoutTextSearchable (~> 0.33.1)
  - FlipperKit/FlipperKitNetworkPlugin (~> 0.33.1)
  - FlipperKit/FlipperKitReactPlugin (~> 0.33.1)
  - FlipperKit/FlipperKitUserDefaultsPlugin (~> 0.33.1)
  - FlipperKit/SKIOSNetworkPlugin (~> 0.33.1)
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - lottie-ios (from `../node_modules/lottie-ios`)
  - lottie-react-native (from `../node_modules/lottie-react-native`)
  - RCTRequired (from `../node_modules/react-native/Libraries/RCTRequired`)
  - RCTTypeSafety (from `../node_modules/react-native/Libraries/TypeSafety`)
  - React (from `../node_modules/react-native/`)
  - React-Core (from `../node_modules/react-native/`)
  - React-Core/DevSupport (from `../node_modules/react-native/`)
  - React-Core/RCTWebSocket (from `../node_modules/react-native/`)
  - React-CoreModules (from `../node_modules/react-native/React/CoreModules`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - react-native-safe-area-context (from `../node_modules/react-native-safe-area-context`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - ReactCommon/callinvoker (from `../node_modules/react-native/ReactCommon`)
  - ReactCommon/turbomodule/core (from `../node_modules/react-native/ReactCommon`)
  - "RNCMaskedView (from `../node_modules/@react-native-community/masked-view`)"
  - "RNFBApp (from `../node_modules/@react-native-firebase/app`)"
  - "RNFBAuth (from `../node_modules/@react-native-firebase/auth`)"
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNReanimated (from `../node_modules/react-native-reanimated`)
  - RNScreens (from `../node_modules/react-native-screens`)
  - RNSVG (from `../node_modules/react-native-svg`)
  - Yoga (from `../node_modules/react-native/ReactCommon/yoga`)

SPEC REPOS:
  trunk:
    - boost-for-react-native
    - CocoaAsyncSocket
    - CocoaLibEvent
    - Firebase
    - FirebaseAuth
    - FirebaseCore
    - FirebaseCoreDiagnostics
    - Flipper
    - Flipper-DoubleConversion
    - Flipper-Folly
    - Flipper-Glog
    - Flipper-PeerTalk
    - Flipper-RSocket
    - FlipperKit
    - GoogleDataTransport
    - GoogleUtilities
    - GTMSessionFetcher
    - nanopb
    - OpenSSL-Universal
    - PromisesObjC
    - YogaKit

EXTERNAL SOURCES:
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  FBLazyVector:
    :path: "../node_modules/react-native/Libraries/FBLazyVector"
  FBReactNativeSpec:
    :path: "../node_modules/react-native/Libraries/FBReactNativeSpec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  lottie-ios:
    :path: "../node_modules/lottie-ios"
  lottie-react-native:
    :path: "../node_modules/lottie-react-native"
  RCTRequired:
    :path: "../node_modules/react-native/Libraries/RCTRequired"
  RCTTypeSafety:
    :path: "../node_modules/react-native/Libraries/TypeSafety"
  React:
    :path: "../node_modules/react-native/"
  React-Core:
    :path: "../node_modules/react-native/"
  React-CoreModules:
    :path: "../node_modules/react-native/React/CoreModules"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  react-native-safe-area-context:
    :path: "../node_modules/react-native-safe-area-context"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  ReactCommon:
    :path: "../node_modules/react-native/ReactCommon"
  RNCMaskedView:
    :path: "../node_modules/@react-native-community/masked-view"
  RNFBApp:
    :path: "../node_modules/@react-native-firebase/app"
  RNFBAuth:
    :path: "../node_modules/@react-native-firebase/auth"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  RNReanimated:
    :path: "../node_modules/react-native-reanimated"
  RNScreens:
    :path: "../node_modules/react-native-screens"
  RNSVG:
    :path: "../node_modules/react-native-svg"
  Yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga"

SPEC CHECKSUMS:
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  CocoaAsyncSocket: 694058e7c0ed05a9e217d1b3c7ded962f4180845
  CocoaLibEvent: 2fab71b8bd46dd33ddb959f7928ec5909f838e3f
  DoubleConversion: 5805e889d232975c086db112ece9ed034df7a0b2
  FBLazyVector: 4aab18c93cd9546e4bfed752b4084585eca8b245
  FBReactNativeSpec: 5465d51ccfeecb7faa12f9ae0024f2044ce4044e
  Firebase: 919186c8e119dd9372a45fd1dd17a8a942bc1892
  FirebaseAuth: b85c064e0ac60f82486728d50a4803f235687302
  FirebaseCore: 8cd4f8ea22075e0ee582849b1cf79d8816506085
  FirebaseCoreDiagnostics: 7535fe695737f8c5b350584292a70b7f8ff0357b
  Flipper: 6c1f484f9a88d30ab3e272800d53688439e50f69
  Flipper-DoubleConversion: 38631e41ef4f9b12861c67d17cb5518d06badc41
  Flipper-Folly: c12092ea368353b58e992843a990a3225d4533c3
  Flipper-Glog: 1dfd6abf1e922806c52ceb8701a3599a79a200a6
  Flipper-PeerTalk: 116d8f857dc6ef55c7a5a75ea3ceaafe878aadc9
  Flipper-RSocket: 64e7431a55835eb953b0bf984ef3b90ae9fdddd7
  FlipperKit: 6dc9b8f4ef60d9e5ded7f0264db299c91f18832e
  Folly: 30e7936e1c45c08d884aa59369ed951a8e68cf51
  glog: 1f3da668190260b06b429bb211bfbee5cd790c28
  GoogleDataTransport: 8a40cb194ad242b6f6dfe72c14fe40fc67c4dcd7
  GoogleUtilities: 23ad5d79794b8ded1954466d5be6f8f694d3f7f3
  GTMSessionFetcher: 6f5c8abbab8a9bce4bb3f057e317728ec6182b10
  lottie-ios: 496ac5cea1bbf1a7bd1f1f472f3232eb1b8d744b
  lottie-react-native: a664f59f1f298c2696dd0ae07b15cbdfc433cb02
  nanopb: c43f40fadfe79e8b8db116583945847910cbabc9
  OpenSSL-Universal: 8b48cc0d10c1b2923617dfe5c178aa9ed2689355
  PromisesObjC: b48e0338dbbac2207e611750777895f7a5811b75
  RCTRequired: cec6a34b3ac8a9915c37e7e4ad3aa74726ce4035
  RCTTypeSafety: 93006131180074cffa227a1075802c89a49dd4ce
  React: 29a8b1a02bd764fb7644ef04019270849b9a7ac3
  React-Core: b12bffb3f567fdf99510acb716ef1abd426e0e05
  React-CoreModules: 4a9b87bbe669d6c3173c0132c3328e3b000783d0
  React-cxxreact: e65f9c2ba0ac5be946f53548c1aaaee5873a8103
  React-jsi: b6dc94a6a12ff98e8877287a0b7620d365201161
  React-jsiexecutor: 1540d1c01bb493ae3124ed83351b1b6a155db7da
  React-jsinspector: 512e560d0e985d0e8c479a54a4e5c147a9c83493
  react-native-safe-area-context: e200d4433aba6b7e60b52da5f37af11f7a0b0392
  React-RCTActionSheet: f41ea8a811aac770e0cc6e0ad6b270c644ea8b7c
  React-RCTAnimation: 49ab98b1c1ff4445148b72a3d61554138565bad0
  React-RCTBlob: a332773f0ebc413a0ce85942a55b064471587a71
  React-RCTImage: e70be9b9c74fe4e42d0005f42cace7981c994ac3
  React-RCTLinking: c1b9739a88d56ecbec23b7f63650e44672ab2ad2
  React-RCTNetwork: 73138b6f45e5a2768ad93f3d57873c2a18d14b44
  React-RCTSettings: 6e3738a87e21b39a8cb08d627e68c44acf1e325a
  React-RCTText: fae545b10cfdb3d247c36c56f61a94cfd6dba41d
  React-RCTVibration: 4356114dbcba4ce66991096e51a66e61eda51256
  ReactCommon: ed4e11d27609d571e7eee8b65548efc191116eb3
  RNCMaskedView: 5a8ec07677aa885546a0d98da336457e2bea557f
  RNFBApp: 6fd8a7e757135d4168bf033a8812c241af7363a0
  RNFBAuth: 82b94c2f0a851be529a19f5fda2dffb390bfdd7f
  RNGestureHandler: 8f09cd560f8d533eb36da5a6c5a843af9f056b38
  RNReanimated: 955cf4068714003d2f1a6e2bae3fb1118f359aff
  RNScreens: cf198f915f8a2bf163de94ca9f5bfc8d326c3706
  RNSVG: ce9d996113475209013317e48b05c21ee988d42e
  Yoga: 3ebccbdd559724312790e7742142d062476b698e
  YogaKit: f782866e155069a2cca2517aafea43200b01fd5a

PODFILE CHECKSUM: f3418a1b8ea484258f4ef7d30fd84f5c2f7fe855

COCOAPODS: 1.9.3

```

#### `AppDelegate.m`:

```objc
#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <Firebase.h>

#if DEBUG
#import <FlipperKit/FlipperClient.h>
#import <FlipperKitLayoutPlugin/FlipperKitLayoutPlugin.h>
#import <FlipperKitUserDefaultsPlugin/FKUserDefaultsPlugin.h>
#import <FlipperKitNetworkPlugin/FlipperKitNetworkPlugin.h>
#import <SKIOSNetworkPlugin/SKIOSNetworkAdapter.h>
#import <FlipperKitReactPlugin/FlipperKitReactPlugin.h>

static void InitializeFlipper(UIApplication *application) {
  FlipperClient *client = [FlipperClient sharedClient];
  SKDescriptorMapper *layoutDescriptorMapper = [[SKDescriptorMapper alloc] initWithDefaults];
  [client addPlugin:[[FlipperKitLayoutPlugin alloc] initWithRootNode:application withDescriptorMapper:layoutDescriptorMapper]];
  [client addPlugin:[[FKUserDefaultsPlugin alloc] initWithSuiteName:nil]];
  [client addPlugin:[FlipperKitReactPlugin new]];
  [client addPlugin:[[FlipperKitNetworkPlugin alloc] initWithNetworkAdapter:[SKIOSNetworkAdapter new]]];
  [client start];
}
#endif

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  if ([FIRApp defaultApp] == nil) {
    [FIRApp configure];
  }
  
#if DEBUG
  InitializeFlipper(application);
#endif

  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"APP_NAME"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end

```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.16 MB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6308749
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Java: 14.0.1 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

- **Platform that you're experiencing the issue on**:
  - [X] iOS
  - [ ] Android
  - [X] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Interesting. You didn't include your package.json but since it's ios-focused and you put the Podfile.lock in there I was able to see that you've got very up to date firebase-ios-sdk (6.27.1) but you have different GoogleUtilities pod than I have (6.7.0 vs my 6.6.0) which showed me there was a big release today https://firebase.google.com/support/release-notes/ios#version_6280_-_july_14_2020 and it involved a major change to GoogleUtilities: https://github.com/firebase/firebase-ios-sdk/pull/5824

I'm guessing if you pinned GoogleUtilties back to 6.6.0 things would work for you?

In the meantime this needs more triage

**Comment by mikehardy** [comment]
Still hunting for workaround but after updating the pods in my work project (and the whole firebase-ios-sdk to 6.28.0) I reproduce this, I don't think upstream realized it was a build break / breaking change since the headers are labeled 'Private' but it's definitely got an affect here. 

This was working prior to the release today so some form of pinning pod versions back should definitely be the temporary workaround.

**Comment by croossin** [comment]
@mikehardy Pinning `GoogleUtilities` to `6.6.0` fixed the build error.  Sounds unfortunate that I tried today when they released the new version, ha!  Let me know if you need any debugging assistance from my end.

**Comment by mikehardy** [comment]
Yes, had you tried mere hours earlier you would have been saying "wow, that was easy and I can't believe how much functionality is available to me, all working beautifully" haha. But nope

**Comment by mikehardy** [comment]
A naive attempt at a local patch was ineffective, I petitioned the upstream change author for advice, https://github.com/firebase/firebase-ios-sdk/pull/5824/files#r454737507

**Comment by mikehardy** [comment]
For anyone else that hits this here's the patch for [patch-package](https://github.com/ds300/patch-package) until there is a release here

Confirmed working up to firebase-ios-sdk 6.27.1, it will **not** work with 6.28.0. You must not use 6.28.0 until we figure this out

`cat patches/@react-native-firebase+messaging+7.4.2.patch`

```
 
diff --git a/node_modules/@react-native-firebase/messaging/RNFBMessaging.podspec b/node_modules/@react-native-firebase/messaging/RNFBMessaging.podspec
index 1c29e44..5e998a7 100644
--- a/node_modules/@react-native-firebase/messaging/RNFBMessaging.podspec
+++ b/node_modules/@react-native-firebase/messaging/RNFBMessaging.podspec
@@ -40,6 +40,7 @@ Pod::Spec.new do |s|
   # Firebase dependencies
   s.dependency          'Firebase/Analytics', firebase_sdk_version
   s.dependency          'Firebase/Messaging', firebase_sdk_version
+  s.dependency          'GoogleUtilities', '6.6.0'
 
   if defined?($RNFirebaseAsStaticFramework)
     Pod::UI.puts "#{s.name}: Using overridden static_framework value of '#{$RNFirebaseAsStaticFramework}'"
```

**Comment by sofianegargouri** [comment]
Got the same issue with Auth 😉

**Comment by nive745** [comment]
Got same issue with Auth..... It's freaking....

**Comment by VjIntesols** [comment]
I am receiving the same with Firebase push notification in React Native.

**Comment by nive745** [comment]
> @mikehardy Pinning `GoogleUtilities` to `6.6.0` fixed the build error. Sounds unfortunate that I tried today when they released the new version, ha! Let me know if you need any debugging assistance from my end.

Can you help how to fix it in RNFBAuth and RNFBCrashlytics?

**Comment by ricklove** [comment]
Linking the related stack overflow question: https://stackoverflow.com/questions/62905585/googleutilities-appdelegateswizzler-private-gulapplication-h-file-not-found?noredirect=1#comment111248890_62905585

**Comment by croossin** [comment]
@mikehardy I noticed after pinning GoogleUtilities to 6.6.0, when trying to use [Email/Password Signin](https://rnfirebase.io/auth/usage#emailpassword-sign-in) - I kept receiving this error: `error signing in [Error: [auth/weak-password] The given password is invalid.]` no matter how complex I made the password.

Can you confirm that this is in fact a different issue?

**Comment by mikehardy** [comment]
Upstream has a fix coming. https://github.com/firebase/firebase-ios-sdk/pull/6050

**Comment by mikehardy** [comment]
You pin it like this, here's the PR, with a patch-package patch included https://github.com/invertase/react-native-firebase/pull/3939 - it was already linked above

**Comment by mikehardy** [comment]
GoogleUtilities 6.7.1 has been released. `pod update` (maybe `pod update --repo-update`) should resolve this for everyone. The google team responded to this extremely quickly with an official release, impressive.

**Comment by mrousavy** [comment]
@mikehardy On the newest version I'm still getting the error (now even for dynamic links). See https://github.com/invertase/react-native-firebase/issues/4040
