### ISSUE TITLE
[🐛] Bug Report Title - CHANGE ME 

### ISSUE THREAD

**Issue by Servo97** [invertase/react-native-firebase#4666]
## Issue

Describe your issue here
Library version: "@react-native-firebase/functions": "^10.1.1",

When calling 
`await functions().httpsCallable(**functionName**)({**options**})`
the following error occurs:

TypeError: _internal.NativeFirebaseError.getStackWithMessage is not a function. (In '_internal.NativeFirebaseError.getStackWithMessage("Error: " + _this.message, nativeErrorInstance.jsStack)', '_internal.NativeFirebaseError.getStackWithMessage' is undefined)
---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by TowhidKashem** [comment]
Had the same issue, it was fixed by passing an empty object in the function call:

Before:

`const { data } = await functions().httpsCallable('listProducts')();`

After:

`const { data } = await functions().httpsCallable('listProducts')({});`

**Comment by mrozanski** [comment]
We're having this issue with 10.5.1 on Android and iOS.
The empty object doesn't solve it, besides, we need to pass options in our case.

**Comment by mikehardy** [comment]
This issue has no real title, and no template. I suggest someone open a fresh issue with the information that would help us locate the problem, and ideally an App.js that we could drop in a clean project that reproduces it

**Comment by tarung** [comment]
> We're having this issue with 10.5.1 on Android and iOS.
> The empty object doesn't solve it, besides, we need to pass options in our case.

Hi, Were you able to solve this issue ?

**Comment by mrozanski** [comment]
@tarung 
No. We abandoned callable cloud functions because they proved to be unreliable for large bulk operations and switched to a custom API in Rails.
You can still call them using fetch or with any you can perform a GET from your app if you're facing this issue with this package.

@mikehardy
Thanks for your reply. You're right. This ticket doesn't follow protocol. I found it googling the error message and if we hadn't decided to move away from callables I would have created a more useful one.

**Comment by mikehardy** [comment]
Sounds good - FWIW, for small(-ish? not sure how big my cloud functions are relative to @mrozanski 's) I have not had any reliability issues. Some of mine do run up to 90 seconds or so and they all complete fine though I have to expand the timeout a bit.

**Comment by ramonhoyo** [comment]
Same behavior, errors on fireabase-functions becomes into this error:

```
TypeError: _internal.NativeFirebaseError.getStackWithMessage is not a function. (In '_internal.NativeFirebaseError.getStackWithMessage("Error: " + _this.message, nativeErrorInstance.jsStack)', '_internal.NativeFirebaseError.getStackWithMessage' is undefined)
``` 

Is there any solution for this error?

**Comment by mikehardy** [comment]
The issue is very poorly specified, so I couldn't say what the problem is

With a reproduction (https://stackoverflow.com/help/minimal-reproducible-example) in the form of a fully self-contained `App.js` I could drop in a clean skeleton project (https://github.com/mikehardy/rnfbdemo/blob/master/make-demo.sh) I might be able to say more
