### ISSUE TITLE
Phone auth on android - error when confirming code 'auth/session-expired'

### ISSUE THREAD

**Issue by omgo** [invertase/react-native-firebase#530]
### Issue
Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error `auth/session-expired` - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?

```
sendCode() {
  firebase.auth().signInWithPhoneNumber(this.store.phoneNumber)
    .then(confirmResult => {
      this.store.setConfirmResult(confirmResult)
    }).catch(error => {
      console.log(error)
    })
}

authorize() {
  this.store.confirmResult.confirm(this.store.code)
    .then(user => {
      console.log(user)
    })
    .catch(error => {
      console.log(error)
    })
}
```

### Environment

1. Application Target Platform: Android

2. Development Operating System: macOS Sierra

3. Build Tools: Android Studio 2.3.3, Android SDK 26.1.1

4. React Native version: 0.49.3

5. RNFirebase Version: 3.0.3

6. Firebase Module: auth (phone)

**Comment by omgo** [comment]
Does anyone have the same problem?

**Comment by chrisbianca** [comment]
@omgo Sorry for the lack of response, this one slipped through.

I've been doing lots of testing with `signInWithPhoneNumber` recently and haven't come across this issue so I'm not really sure what to suggest.

The only thing I can think is that there's too long a time happening between the initial request and confirming the code?

Just to confirm, are you handling the autoverified case in Android using the `onAuthStateChanged` listener?

**Comment by omgo** [comment]
@chrisbianca thank you for your answer.
Yes, I'm using onAuthStateChanged, and you know, actually phone auth sometimes is working, it really didn't work a few days ago (after getting code we were sending it in next 10 seconds - and 'session expired') but now it's working almost every time (sometimes still 'session expired'), it's like a magic)) I can't understand. Looks like issue can be closed

**Comment by chrisbianca** [comment]
@omgo Sounds like it might be an internal Firebase issue then.  I'm going to close, but please re-open if you keep running into problems.

**Comment by sfratini** [comment]
@omgo I am having the same issue. In your case was consistent for a period of time and then it worked? Or just random? I'll try tomorrow but I wanted to be sure what is going on. Thanks!

**Comment by rajeshzmoke** [comment]
facing the same issue as @sfratini 
React native 0.51.0
React native Firebase 
Android 7.1.1 

And i would like to add another point that the above mentioned issue happens only on a MI device

**Comment by dmacan23** [comment]
Is there any update on this issue? I am still receiving it. 
Oneplus 5, 
Android 8.0.0, 
RN 0.53, 
RN Firebase 3.2.7,
Firebase 11.6.0

**Comment by rajeshzmoke** [comment]
If u have an onauthstatechanged() listener and also if you're trying to manually verify the phone number , you will get session expired everytime on Android ...

Reason :
- onauthstatechanged () will verify as soon as u get sms (automatically) ..so if you're trying to verify manually using the same sms it won't work.

Hope this helps.

**Comment by adirzoari** [comment]
@omgo  I'm facing the same issue. did you find solution?

**Comment by nomi9995** [comment]
i am also facing same issue on android 7.0 only

**Comment by WilliamAnputra** [comment]
I have the same problem on  android MI A1

**Comment by tamirrab** [comment]
@WilliamAnputra How can I sign in with verifyPhoneNumber?

**Comment by AmmarAshfaq** [comment]
why firebase is still not solved firebase phone authentication verify code session expire? I am facing the same issue verify code expires within 10 seconds

**Comment by mikehardy** [comment]
@AmmarAshfaq this does not happen to me. I am literally testing this functionality on my app right now, works fine with all currently versions at least (RN0.59.5 / RNFirebase 5.3.1 / fully current firebase deps in gradle etc)

**Comment by AmmarAshfaq** [comment]
@mikehardy can you give me some hint because I am facing the same issue

**Comment by sfratini** [comment]
The reason why this is happening (most likely) is it because Android already authenticated in the background and you are manually trying to sign in. Just implemente the onAuthStateChanged method and forget about the manual signIn, or just implement it for iOS and for Android just have another logic. 

You will see that you get the user data even before the framework updates and recognizes the SMS.

**Comment by mikehardy** [comment]
sounds about right, I implemented it based on the example template in the docs on phoneVerify, and in my analytics at least, about 80% of android users are auto-verified by the framework so I imagine if you don't get this right you'll see the timeouts (false positives, really) all the time

**Comment by MobileDev418** [comment]
I am still receiving it. Is there anyone to help me?

Samsung Galaxy S7,
Android 8.0.0,
RN 0.57.5,
RN Firebase 5.3.0,
com.google.firebase:firebase-auth:17.0.0

**Comment by vuthanhtrung0504** [comment]
Any solution yet?
Samsung S8 Android 9.0,
RN 0.59.9,
RN Firebase 5.5.4,

**Comment by sfratini** [comment]
> 
> 
> Any solution yet?
> Samsung S8 Android 9.0,
> RN 0.59.9,
> RN Firebase 5.5.4,

Just see my answer above. Most likely the firebase already authenticated in the background right after getting the SMS and you are trying to confirm a code that was already confirmed.

https://github.com/invertase/react-native-firebase/issues/530#issuecomment-484480100

**Comment by brascene** [comment]
I've encountered this issue on newer Android devices only, and what they do is just after code is sent to your device, somehow, you're automatically signed in, which means: no need to open SMS, no need to enter code anywhere, which is imho really awful. I have additional screens between code confirmation and letting user into the app, which now I have to tweak, on Android only. 
I was hoping to see that some kind of disabling this "feature" is possible, but nothing so far?

**Comment by Bilal-Abdeen** [comment]
Apparently, some recent versions of Android are smart enough to receive the SMS verification code and use it to authenticate the user. This **authentication happens in the background** while **the user still receives the verification code in an SMS.** When the user tries to enter the verification code, he/she gets a message that the verification code expired, **because Android has already used it (in the background) and has already logged in the user!** To double-check that, check the Firebase Console. You should find that this new user has been added to the list of users. 

To avoid receiving the verification code expiry message, we need to set up **a listener** for "**authentication changes**." As soon as Android logs in the user in the background, this listener should navigate the user away from the login screen, in which he/she was supposed to enter the verification code. 

For an example implementation of this listener, please, check out my answer to the following stackoverflow question. 
https://stackoverflow.com/questions/57054891/the-sms-code-has-expired-please-re-send-the-verification-code-to-try-again

**Comment by mikehardy** [comment]
@Bilal-Abdeen or the doc example https://rnfirebase.io/docs/v5.x.x/auth/phone-auth#Example (for RFNBv5) - it appears that it has not been ported to v6 but a PR for the official doc would be useful, the indicated method (using the listener to check for auto verify) is definitely the recommended style

**Comment by tunm1228** [comment]
Hello, I'm using phone auth, and it works on ios, but dont on android. After confirming code I get the error auth/session-expired - ofc I understand that is it mean, but I don't understand why, and how to fix it. Could you help me?

**Comment by mikehardy** [comment]
@tunm1228 android has the power to "auto verify" at the SDK level when it sees a code come through. Your code is already used in this case. Don't confirm explicitly unless you have to. Use the auth change listener instead

**Comment by aadityapaliwal94** [comment]
@mikehardy I am also getting the same problem even on iOS. And there is no callback on the onAuthStateChanged listener. Could you please help?

**Comment by mikehardy** [comment]
@aadityapaliwal94 no time will be spent on closed issues typically. New issue, follow the template, using current stable versions, and please provide a minimal reproducible example App.js for reproduction

**Comment by Akhilbisht12** [comment]
Changing the Confirm.confirm(code) to const credential = auth.PhoneAuthProvider.credential(confirm.verificationId, code);
worked for me

**Comment by rkumardas** [comment]
ok ,guys I am battling with same  is issue and @Akhilbisht12 way work thanks, but I discover another way which worked for me.
Put this     android:importantForAutofill="no"   in xml file in android folder under activity .

**Comment by rkumardas** [comment]
You can add this  android:importantForAutofill="no"  to xml file in android it worked for me

**Comment by Serezhazp** [comment]
Hi. Is this issue really fixed? We've facing with this strange issue on some devices/locations (in different countries it works different, as per our test - mostly we see it in Denmark).
Code is entered immediately after receiving it, but there is error:

`[Error: [auth/session-expired] The sms code has expired. Please re-send the verification code to try again.]`

I've tried to change the confirmation part as per @Akhilbisht12 comment but the app behaves the same and I'm still getting this error.

Any suggestions how to fix it or it's totally on Firebase side?

**Comment by mikehardy** [comment]
@Serezhazp unsure - we do see a lot of odd behavior *like* this (but maybe not this...) related to users using VPNs. Firebase has all manner of failures when a user is on a VPN. That could be it? In the end this will be either in firebase-ios-sdk or firebase-android-sdk though, we have no control over it at our react-native wrapper layer. If it works at all, that means we are wrapping the APIs correctly, and if it fails sometimes that means the underlying SDKs and/or firebase backend is doing something underneath us that we likely have no control over

**Comment by musabgulfam** [comment]
> > Any solution yet?
> > Samsung S8 Android 9.0,
> > RN 0.59.9,
> > RN Firebase 5.5.4,
> 
> Just see my answer above. Most likely the firebase already authenticated in the background right after getting the SMS and you are trying to confirm a code that was already confirmed.
> 
> [#530 (comment)](https://github.com/invertase/react-native-firebase/issues/530#issuecomment-484480100)

The documentation must mention these things. In the documentation it says, that we must manually enter the code and pass it to `confirm.confirm(otp_code)` method. Automatic verification of OTP is nowhere mentioned in the docs(https://rnfirebase.io/auth/phone-auth).

**Comment by musabgulfam** [comment]
> @omgo Sounds like it might be an internal Firebase issue then. I'm going to close, but please re-open if you keep running into problems.

This issue still exists...

**Comment by mikehardy** [comment]
If there is something missing in the documentation, please hit the edit button on the top right of all pages and propose the missing part - we're not sure what is missing. It might be subtle but I see this:

> Upon successful sign-in, any [onAuthStateChanged](https://rnfirebase.io/auth/usage#listening-to-authentication-state) listeners will trigger with the new authentication state of the user.

The point there is that the listeners and the user state is how you'll know about auto-signin. You could request signin, be waiting to enter a code but *while waiting* boom you get onAuthStateChanged (or onUserChanged which will handle user reload even) indicating that you are signed in now. That's it, you're signed in.

In most navigation flows you have a signed in / signed out set of screens that auto-switch based on user existing, auth.currentUser will all the sudden start existing after auto-OTP verification so really your whole component tree should disappear and remount as the signed in set of screens and you're done.

This issue is from 2017, so @musabgulfam open a new issue if you still see a problem, however, please be very aware that I currently have no problem using phone auth in real projects so you will need to be really thorough on the issue *and* make sure with a clean example app that it's not your local project with a problem:

https://stackoverflow.com/help/how-to-ask
https://stackoverflow.com/help/minimal-reproducible-example
https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh (to kick out a skeleton app with clean up to date dependencies, to check your API usage)

**Comment by MuhammadSaad420** [comment]
My phone authentication is working fine, but if I sign out of one account and prompt to create another account with different credentials I am getting this error...I think it has something to do with signOut functionality(token expiration kind of stuff)...can anybody help?

**Comment by dawahsoftofficial** [comment]
Solution:

Mistakes developers are doing due to lack of research. First make sure of the following:

1. Firebase has correct SHA keys (From Play Store), Google service JSON file is correctly downloaded, Android verification check API is enabled with correct service account.
2. When SMS is received, modern devices authenticate it in background so the OTP page should be redirected to the success page. (This causes Auth / Session-expired)
3. You dont get SMS everytime after the first time you ask as Firebase has some rules, and one of them is the Authentication list they keep, that means you dont need and SMS, just use UID
3. To log in again, SMS verification is not required, Firebase UID is required as Firebase keep a cached copy of the UID in the app instance in your phone:

If you need to get an AuthCredential object for the user's account, pass the verification code from the confirmation result and the verification code to PhoneAuthProvider.credential instead of calling confirm:

var credential = firebase.auth.PhoneAuthProvider.credential(confirmationResult.verificationId, code);
Then, you can sign in the user with the credential:

firebase.auth().signInWithCredential(credential); 

That might help

**Comment by musabgulfam** [comment]
@mikehardy, when the `onAuthStateChange` function executes upon successful login, can we get the OTP from that, because we have to show the users, that the OTP has successfully been fetched.

**Comment by mikehardy** [comment]
No, but it will be clear that the system fetched it automatically fir you, or they would not be authorized, calling the listener. So you can just say something like "hey we automatically got the code and you're all set..."

**Comment by musabgulfam** [comment]
Alright, thank you very much @mikehardy, really appreciate it.

**Comment by Gxmadix** [comment]
> Changing the Confirm.confirm(code) to const credential = auth.PhoneAuthProvider.credential(confirm.verificationId, code); worked for me

did you ever check what was done inside the credential function? 
`const providerId = 'phone';
  static credential(verificationId, code) {
    return {
      token: verificationId,
      secret: code,
      providerId,
    };
  }`
  
  for sure it will pass, since you are juste passing your code inside an object, you can also have
 ` auth.PhoneAuthProvider.credential(confirm.verificationId, "shouln'd pass");`  and it will not complain at all.
 
 There are 2 correct solutions, implement strategy by listening onAuthStateChanged or use **verifyPhoneNumber** which is just checking the phone number as shown in this example from the [doc](https://rnfirebase.io/auth/phone-auth#mfa-like-account-creation).

**Comment by Mufeez** [comment]
> * onauthstatechanged ()

Thanks for this ,i was facing the same issue ,will try out this solution

**Comment by sleekLancelot** [comment]
> I've encountered this issue on newer Android devices only, and what they do is just after code is sent to your device, somehow, you're automatically signed in, which means: no need to open SMS, no need to enter code anywhere, which is imho really awful. I have additional screens between code confirmation and letting user into the app, which now I have to tweak, on Android only.
> I was hoping to see that some kind of disabling this "feature" is possible, but nothing so far?

My sentiment exactly!

**Comment by sleekLancelot** [comment]
> I've encountered this issue on newer Android devices only, and what they do is just after code is sent to your device, somehow, you're automatically signed in, which means: no need to open SMS, no need to enter code anywhere, which is imho really awful. I have additional screens between code confirmation and letting user into the app, which now I have to tweak, on Android only.
> I was hoping to see that some kind of disabling this "feature" is possible, but nothing so far?

My sentiment exactly!

**Comment by joaqo** [comment]
> @mikehardy I am also getting the same problem even on iOS. And there is no callback on the onAuthStateChanged listener. Could you please help?

Where you able to solve it in iOS? I am facing the same issue on iOS.

**Comment by SiddeshThorat** [comment]
All the above approaches are working fine in my development build, however when I deploy my android application to playstore, I start getting this error. I have added necessary signing keys in firebase console but still getting the same error

can someone please help me with this issue

**Comment by Linuhusainnk** [comment]
Any update on this issues,

can anyone provide the sample code, on how to handle this scenario
