### ISSUE TITLE
[🐛] 'FirebaseFunctions/FirebaseFunctions-Swift.h' file not found

### ISSUE THREAD

**Issue by nicolas-wl** [invertase/react-native-firebase#6382]
When building for iOS, I keep getting the following error:

```
In file included from .../node_modules/@react-native-firebase/storage/ios/RNFBStorage/RNFBStorageModule.m:18:
.../my-app/ios/Pods/Headers/Private/Firebase/Firebase.h:54:13: fatal error: 'FirebaseFunctions/FirebaseFunctions-Swift.h' file not found
    #import <FirebaseFunctions/FirebaseFunctions-Swift.h>
```
dependencies are all at latest version
```
    "@react-native-firebase/app": "^15.1.1",
    "@react-native-firebase/auth": "^15.1.1",
    "@react-native-firebase/firestore": "^15.1.1",
    "@react-native-firebase/functions": "^15.1.1",
    "@react-native-firebase/messaging": "^15.1.1",
    "@react-native-firebase/storage": "^15.1.1",
```

podfile

```
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'MyApp' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  $RNFirebaseAsStaticFramework = true

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
target 'MyAppTests' do
inherit! :complete
# Pods for testing
end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
  
  
```

**Comment by mikehardy** [comment]
:thinking:  Hmm

I don't recognize these, but I see them show up pretty frequently now that use_frameworks is required. Why are these here? Where does the recommendation to turn them on come from? What problem do they solve, if you cannot build currently?

```

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
```

Flipper is not going to work with use_frameworks - that's not fixed yet as far as I know:

```
  use_flipper!()
```

Does my demo script (still on 0.69.0, sorry - but reasonably representative) work for you? https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

Does it still work if you chop the installed modules down to just the ones you use?

**Comment by octiva** [comment]
Hey, im also experience the same issue, and have a very similar `Podfile`. This issue only seems to occur after adding firebase storage.

@mikehardy the usage of the specific `pod 'Firebase', :modular_headers => true`... come from [this issue comment](https://github.com/invertase/react-native-firebase/issues/6332#issuecomment-1182831998)

we are using these in leu of the `use_framework` due to its incompatibility with Flipper.

I believe the issue may also be related to a recent issue in FirebaseIOS [here](https://github.com/firebase/FirebaseUI-iOS/issues/1028), which looks to have been resolved [here](https://github.com/firebase/FirebaseUI-iOS/pull/1029).
Would be interested to know if the react-native-firebase package has incorporated these changes.

Keen to discuss, and if I find a working solution with Flipper, I will provide.

**Comment by dpyeates** [comment]
I'm getting this as well with FB Storage

![Screenshot 2022-07-19 at 18 06 38](https://user-images.githubusercontent.com/944670/179930788-4c68fe62-a862-4910-845d-e37d2af9c8e6.png)

@mikehardy I have manually incorporated the pod changes from your script. Here is my current pod file

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

target 'RNApp' do
  config = use_native_modules!

  $FirebaseSDKVersion = '9.3.0'
  $RNFirebaseAsStaticFramework = true
  pod "FirebaseCoreInternal", :modular_headers => true
  pod "FirebaseCore", :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod "FirebaseStorageInternal", :modular_headers => true
  pod "FirebaseAppCheckInterop", :modular_headers => true
  pod "FirebaseAuthInterop", :modular_headers => true
  pod "FirebaseCoreExtension", :modular_headers => true
  pod "FirebaseCrashlytics", :modular_headers => true
  pod "GoogleUtilities", :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'rnmapbox-maps', :path => '../node_modules/@rnmapbox/maps', :inhibit_warnings => false

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # This makes the iOS build much quieter.
        # In particular libevent dependency, pulled in by react core / flipper items is ridiculously noisy
        config.build_settings["GCC_WARN_INHIBIT_ALL_WARNINGS"] = "YES"
        # Another workaround needed for static framework build
        # Bitcode will not work with it, but that's okay, bitcode is deprecated
        # https://github.com/facebook/react-native/pull/34030#issuecomment-1171197734
        config.build_settings["ENABLE_BITCODE"] = "NO"
        # Required for Apple Silicon Macs
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
      end
    end
    # Apple Silicon builds require a library path tweak for Swift discovery or we get "symbol not found"
    installer.aggregate_targets.first.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['LIBRARY_SEARCH_PATHS'] = ['$(inherited)', '$(SDKROOT)/usr/lib/swift']
      end
    end
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    $RNMapboxMaps.post_install(installer)
  end

end

```

**Comment by mikehardy** [comment]
@octiva i just dud a release last night that has latest iOS SDK dependency so if it's released, it's available here

Not sure what's going on with the storage compile fail? Dies the make-demo.sh I link everywhere work? It has storage and it works for me ? 🤔

**Comment by octiva** [comment]
@mikehardy I cant see the new release version, will this be `v15.1.2`?

**Comment by mikehardy** [comment]
> @mikehardy I cant see the new release version, will this be `v15.1.2`?

Apologies thought I published but did not, job running now...

**Comment by octiva** [comment]
@mikehardy I just tested `v15.2.0` and unfortunately im still getting the same build error. 

I have investigated a little more, but with no success. Will be moving on from this and following a less ideal path of using the Firebase web package in the app for Storage. 

Will likely look to pick this back up at some point, but my gut feeling is that it is upstream of this package and likely needs to be resolved in `FirebaseUI-iOS`.

**Comment by mikehardy** [comment]
I read through the changes in linked FirebaseUI area, and this is the style of change they did:

https://github.com/firebase/FirebaseUI-iOS/pull/1029/files#diff-96e8c12e050b3b6165fc44b0c8302fcae849e20049f7bc93ff24c1ded1d64303

```
#if __has_include(<FirebaseStorage/FirebaseStorage.h>)
  // Firebase 8.x
  #import <FirebaseStorage/FirebaseStorage.h>
#elif __has_include(<FirebaseStorage/FirebaseStorage-Swift.h>)
  // Firebase 9.0+
  #import <FirebaseStorage/FirebaseStorage-Swift.h>
#else
  @import FirebaseStorage;
#endif
```

We are all 9+ though, so we just changed the import. I think cocoapods might generate that with `use_frameworks`, as that seems to be the variable here, that this is happening and if I understand correctly, the projects are attempting to set `$RNFirebaseAsStaticFramework` to true and use_modular_headers but *not* set `use_frameworks` itself ?

**Comment by dpyeates** [comment]
@mikehardy "if I understand correctly, the projects are attempting to set $RNFirebaseAsStaticFramework to true and use_modular_headers but not set use_frameworks itself ?", yes that is exactly the case. I cannot use use_frameworks as I also use react_native_skia which does not work with frameworks. The other FB modules work OK, it is just storage that seems to have an issue.

**Comment by mikehardy** [comment]
I think based on a thread upstream that cocoapods generates the Swift bridging header file for storage, only in response to the use frameworks toggle. This may be the fundamental reason for the new requirement to use that toggle, perhaps @paulb knows that for sure

**Comment by Fortidude** [comment]
```
In file included from /client/node_modules/@react-native-firebase/app/ios/RNFBApp/RNFBAppModule.m:18:
/client/ios/Pods/Headers/Private/Firebase/Firebase.h:54:13: fatal error: 'FirebaseFunctions/FirebaseFunctions-Swift.h' file not found
    #import <FirebaseFunctions/FirebaseFunctions-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

RN 0.68, firebase 15.2.0,  podfile:

```
  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseStorageInternal', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
```


Any ideas? 🤔

**Comment by mikehardy** [comment]
@Fortidude this looks like the equivalent problem from storage except for functions. The firebase-ios-sdk release notes are clear, use_frameworks is required. Are you using that flag in your podfile? @paulb777 may be able to elaborate on this specific integration need in cocoapods? I had enough time just now to properly tag him in 😅

**Comment by paulb777** [comment]
While the `modular_headers` workarounds may work for the other Firebase pods, with Firebase 9, frameworks are required for FirebaseStorage and FirebaseFunctions.

**Comment by ithustle** [comment]
> While the `modular_headers` workarounds may work for the other Firebase pods, with Firebase 9, frameworks are required for FirebaseStorage and FirebaseFunctions.

@paulb777 can you show how to user `modular_headers`?

@mikehardy 

> The firebase-ios-sdk release notes are clear, use_frameworks is required
`use_frameworks` is conflicting with `use_flipper` ... How can we get away of that?

**Comment by mikehardy** [comment]
@ithustle you cannot get away from it I think.

Flipper must be fixed to work in `use_frameworks` mode, or you must disable Flipper, or you must stay on react-native-firebase <= v14

There is no other way I'm aware of

I'm working on these things (Flipper + use_frameworks compatibility, and Hermes + use_frameworks compatibility which will hopefully be in react-native 0.70) but it will take some time, months I suspect.

So I'm going to close this as a sort of "blocked by upstream" resolution.

for Functions and Storage you must have `use_frameworks` set. For others, at least for now, you may import them directly with modular_headers set but **it is not supported**, it just happens to work for now.

The `use_frameworks` setting does cause problems with other modules, and with Flipper, and with Hermes, but those are problems with those modules, with Flipper and with Hermes, and should be pursued as problems there. I'm doing that with Flipper and Hermes but now with other modules, I'll need other people to pursue those.

**Comment by codekojo** [comment]
> I'm getting this as well with FB Storage
> 
> ![Screenshot 2022-07-19 at 18 06 38](https://user-images.githubusercontent.com/944670/179930788-4c68fe62-a862-4910-845d-e37d2af9c8e6.png)
> 
> I can confirm that if I remove @react-native-firebase/storage from my build then things work OK.

Same Error

**Comment by codekojo** [comment]
> I ended up downgrading to firebase@14 all the firebase packages to be able to use storage with flipper.

Can you share you package.json?

**Comment by elinahovakimyan** [comment]
Here are the packages I use and the Podfile
<img width="374" alt="Screen Shot 2022-07-26 at 00 25 19" src="https://user-images.githubusercontent.com/30688702/180868555-9baab1d1-6e57-4c28-bd64-b7cbbb17d4c9.png">
<img width="595" alt="Screen Shot 2022-07-26 at 00 23 46" src="https://user-images.githubusercontent.com/30688702/180868570-5d50eb09-925f-4b45-ae18-0cbc2ce1ab07.png">

**Comment by juanctecdam** [comment]
Little frustating... I need to use Appcheck and as soon as I upgrade to version 15, I can't get a thing to work..

**Comment by ithustle** [comment]
> Little frustating... I need to use Appcheck and as soon as I upgrade to version 15, I can't get a thing to work..

@juanctecdam, welcome to the club

**Comment by juanctecdam** [comment]
@ithustle Thing is that I need to add to my project AppCheck which depends on the latest version(15) of RN Firebase. I tried to make it as modules, but it always complains about FirebaseStorage-Swift. I tried with use_frameworks and that stopped complaining about this library but I have another library not compiling.
Frustrating cause I can't get to fix this and we need a solution.

**Comment by guthriet1230** [comment]
Any progress here? I'm stuck with the same error specific to Firebase Storage only (@15.2)

**Comment by mikehardy** [comment]
@juanctecdam AppCheck has been available for more than a year, it is available in v14.

Firebase storage and Firebase functions require `use_frameworks!` in your Podfile, it's what generates those files. If you can't use `use_frameworks`, and you ned functions and/or storage, you can't use v15. There's no simpler way to put it unfortunately. Use v14 in that case and help in the underlying issues (with flipper or whatever the 3rd party module is that has a problem) in order to get `use_frameworks!` to work then this whole thing will move forward and get easier for everyone

**Comment by gitcoder-23** [comment]
hi,
I am facing same issue  fatal error: 'FirebaseStorage/FirebaseStorage-Swift.h' file not found #import <FirebaseStorage/FirebaseStorage-Swift.h> .. please help to fix this problem

**Comment by mikehardy** [comment]
@gitcoder-23 that's what you see if you do not enable `use_frameworks! :linkage => :static` in your Podfile. Storage and functions require use frameworks unconditionally, the workarounds others mention are only valid temporarily (until other modules require it unconditionally) and are not valid for storage and functions. My last comment above states the same.

**Comment by mikehardy** [comment]
@gitcoder-23 you **must** read the instructions. Flipper is *not* compatible with `use_frameworks`. This may not be what you want to hear but is nevertheless reality, and is documented: 

https://rnfirebase.io/#altering-cocoapods-to-use-frameworks (big note there)
https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#breaking-changes Huge breaking changes note there

**Comment by kaliseo34** [comment]
> @gitcoder-23 you **must** read the instructions. Flipper is _not_ compatible with `use_frameworks`. This may not be what you want to hear but is nevertheless reality, and is documented:
> 
> https://rnfirebase.io/#altering-cocoapods-to-use-frameworks (big note there) https://github.com/invertase/react-native-firebase/blob/main/CHANGELOG.md#breaking-changes Huge breaking changes note there

Hi,

Disabling Hermes & Flipper causes app crash on build by my side.. I'll need another solution to manage files for the moment :s

Anybody found the solution ?

**Comment by mikehardy** [comment]
> Disabling Hermes & Flipper causes app crash on build by my side

That's really unexpected, if you provided any sort of details (https://stackoverflow.com/help/how-to-ask) I/we might be able to help. I can tell you that it should work though, I just re-ran my build test rig yesterday and it was fine https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by kaliseo34** [comment]
I made some changes regarding your script : 
> Replacing use_frameworks! by use_frameworks! :linkage => :static
> Moving $RNFirebaseAsStaticFramework = true from top of file to next line of use_frameworks
> Uncomment line :flipper_configuration => FlipperConfiguration.enabled, & remplace enabled with disabled

And it worked !

Thanks a lot for your help !

**Comment by danias** [comment]
> I made some changes regarding your script :
> 
> > Replacing use_frameworks! by use_frameworks! :linkage => :static
> > Moving $RNFirebaseAsStaticFramework = true from top of file to next line of use_frameworks
> > Uncomment line :flipper_configuration => FlipperConfiguration.enabled, & remplace enabled with disabled
> 
> And it worked !
> 
> Thanks a lot for your help !

Can you please post the whole of your pod file?

**Comment by mikehardy** [comment]
@danias you can run this script any time

I keep it up to date / in sync with current react-native as I work with react-native releases group to test new releases so it's always pretty fresh

It generates a Podfile that works https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh

**Comment by alexander0205** [comment]
Is working for me with the version 14.11.1 and $FirebaseSDKVersion = '8.15.0'

**Comment by alexander0205** [comment]
> Here are the packages I use and the Podfile <img alt="Screen Shot 2022-07-26 at 00 25 19" width="374" src="https://user-images.githubusercontent.com/30688702/180868555-9baab1d1-6e57-4c28-bd64-b7cbbb17d4c9.png"> <img alt="Screen Shot 2022-07-26 at 00 23 46" width="595" src="https://user-images.githubusercontent.com/30688702/180868570-5d50eb09-925f-4b45-ae18-0cbc2ce1ab07.png">

And adding $FirebaseSDKVersion = '8.15.0'

**Comment by mikehardy** [comment]
It is working for you because you have specifically downgraded to a version of react-native-firebase that includes a version of firebase-ios-sdk from before they converted that to Swift (and before they started requiring `use_frameworks`)

So sure, if you downgrade you can "workaround" this problem.

However, you will have bought yourself other problems. Check the release notes and see if any of the changes between firebase-ios-sdk 8.15.0 and 10.2.0 (soon to be 10.3.0 here) are for issues that will cause you problems https://firebase.google.com/support/release-notes/ios

**Comment by yoannes** [comment]
This worked for me, thanks

https://github.com/invertase/react-native-firebase/issues/6382#issuecomment-1328158923

**Comment by abumubarak-dev** [comment]
I had to remove Flipper and add use_frameworks! :linkage => :static

**Comment by mikehardy** [comment]
> I had to remove Flipper and add use_frameworks! :linkage => :static

Yes, as we document here: https://rnfirebase.io/#altering-cocoapods-to-use-frameworks

**Comment by rishiankush** [comment]
Not at all working for me. I tried every solution. Please check my `podfile` and screenshot for error below:
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks! :linkage => :static
target 'lovelocalPartner' do
  config = use_native_modules!
  # Flags change depending on the env values.
  flags = get_default_flags()
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => true,
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  target 'lovelocalPartnerTests' do
    inherit! :complete
    # Pods for testing
  end
  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```
<img width="1253" alt="Screenshot 2023-01-09 at 1 07 11 PM" src="https://user-images.githubusercontent.com/25289937/211260009-95fdc9a6-6a6a-4e7d-b418-5b27c712bbc4.png">

**Comment by nppull** [comment]
react-native 0.70.0
react-native-firebase 17.0

1. add 
> target 'Example' do
>       config = use_native_modules!
>       $RNFirebaseAsStaticFramework = true
>       use_frameworks! :linkage => :static


2. and comment flipper
>  :flipper_configuration => FlipperConfiguration.enabled,

that work for me.

**Comment by devlprkhan** [comment]
I solved the issue, bellow is my pod file,

`# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# use_modular_headers!
platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => :static
end

target 'BoloNow' do
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseFunctions', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BoloNowTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
`

**Comment by devlprkhan** [comment]
Yes 🥹 🙌, Finally I resolve the issue,

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# use_modular_headers!
platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  # use_frameworks! :linkage => linkage.to_sym
  use_frameworks! :linkage => :static
end

target 'BoloNow' do
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true
  use_frameworks! :linkage => :static

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseStorage', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'GTMSessionFetcher', :modular_headers => true
  pod 'FirebaseFunctions', :modular_headers => true
  pod 'FirebaseMessagingInterop', :modular_headers => true
  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'
  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'BoloNowTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end

**Comment by RKhatri93** [comment]
I've encountered persistent challenges integrating Firebase Cloud Functions and Storage in my React Native project. Despite previous attempts and following suggestions, the error related to 'FirebaseFunctions/FirebaseFunctions-Swift.h' file persists.


<img width="275" alt="Screenshot 2023-12-13 at 3 38 32 PM" src="https://github.com/invertase/react-native-firebase/assets/123067366/c82d574c-69d2-4145-95da-408711b178bf">



**Key Points:**
React Native Version: 0.72.6
Firebase Version: 18.7.3
With new react native architecture
Firebase Pods Configuration: Firebase pods were added with modular headers

**What I've Tried:**
Checked and reconfirmed pod configurations.
Reviewed and ensured Firebase pods were correctly linked.

**Current Impact:**
This issue continues to prevent the utilization of essential Firebase features crucial for the app's functionality.

**Request:**
Seeking further assistance or alternative solutions to resolve this persisting issue and successfully integrate Firebase Cloud Functions and Storage into the React Native project. Any new insights or suggestions are greatly appreciated. Thank you for your ongoing support.

**Comment by mikehardy** [comment]
> Firebase Pods Configuration: Firebase pods were added with modular headers

Don't do that, or if you do that do not come here for support.

`use_frameworks! :linkage => :static` is a **STRICT REQUIREMENT** as documented

You are attempting to use the module contrary to the documentation so no support is provided

**Comment by russplusplus** [comment]
Hey all, I had the same problem and following the "Getting Started" instructions on this page completely solved it for me: https://rnfirebase.io/ 
Might be stating the obvious, but I don't see anyone else mentioning it.

**Comment by n-kulic** [comment]
> @ithustle you cannot get away from it I think.
> 
> Flipper must be fixed to work in `use_frameworks` mode, or you must disable Flipper, or you must stay on react-native-firebase <= v14
> 
> There is no other way I'm aware of
> 
> I'm working on these things (Flipper + use_frameworks compatibility, and Hermes + use_frameworks compatibility which will hopefully be in react-native 0.70) but it will take some time, months I suspect.
> 
> So I'm going to close this as a sort of "blocked by upstream" resolution.
> 
> for Functions and Storage you must have `use_frameworks` set. For others, at least for now, you may import them directly with modular_headers set but **it is not supported**, it just happens to work for now.
> 
> The `use_frameworks` setting does cause problems with other modules, and with Flipper, and with Hermes, but those are problems with those modules, with Flipper and with Hermes, and should be pursued as problems there. I'm doing that with Flipper and Hermes but now with other modules, I'll need other people to pursue those.


Hello, checking back on this.
Has there been progress or changes in debugging React Native in this context (`use_frameworks` conflicting with `use_flipper`)? Any other workarounds besides downgrading firebase packages?
Any insights would be appreciated!

**Comment by tunadag** [comment]
> Hey all, I had the same problem and following the "Getting Started" instructions on this page completely solved it for me: https://rnfirebase.io/

Thanks a lot, actually you made my day, I was struggling with it for hours, that documentation also solved it for me.
