### ISSUE TITLE
[🐛]  Android build failed on expo `~49.0.21`: ERROR:D8: com.android.tools.r8.kotlin.H 

### ISSUE THREAD

**Issue by niyogakiza** [invertase/react-native-firebase#7572]
## Issue

Describe your issue here

Hi, dear Firebase community; there is a problem with Firebase from version `18.0.0` and above. we are on react-native version `0.72.6`, and I tried to bump Firebase from `17.5.0` to the latest Firebase version. However, we experienced an error on the Android build only in the expo app; we are currently on expo version `~49.0.21` 

here are other dependencies we do have:

```
"@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/messaging": "^18.3.0",
	 "@segment/analytics-react-native": "^2.17.0",
    "@segment/analytics-react-native-plugin-firebase": "0.3.11",
    "@segment/sovran-react-native": "^1.0.4",
```

The Build error on android build is this below: 

```
[RUN_GRADLEW] > Task :app:mergeExtDexDebug
[RUN_GRADLEW] ERROR:D8: com.android.tools.r8.kotlin.H
[RUN_GRADLEW] > Task :app:mergeExtDexDebug FAILED

```

```
[RUN_GRADLEW] w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
[RUN_GRADLEW] FAILURE: Build failed with an exception.
[RUN_GRADLEW] * What went wrong:
[RUN_GRADLEW] Execution failed for task ':app:mergeExtDexDebug'.
[RUN_GRADLEW] > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
[RUN_GRADLEW]    > Failed to transform play-services-measurement-api-21.5.0.aar (com.google.android.gms:play-services-measurement-api:21.5.0) to match attributes {artifactType=android-dex, asm-transformed-variant=debug, dexing-enable-desugaring=true, dexing-enable-jacoco-instrumentation=false, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.status=release, org.gradle.usage=java-runtime}.
[RUN_GRADLEW]       > Execution failed for DexingWithClasspathTransform: /Users/.................../.gradle/caches/transforms-3/cfa8871183e4896418536f5fec492947/transformed/jetified-play-services-measurement-api-21.5.0-runtime.jar.
[RUN_GRADLEW]          > Error while dexing.

```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

  "dependencies": {
    "@bugsnag/expo": "^49.0.2",
    "@config-plugins/react-native-blob-util": "^6.0.0",
    "@config-plugins/react-native-pdf": "^6.0.0",
    "@expo/react-native-action-sheet": "^4.0.1",
    "@flagship.io/react-native-sdk": "^3.3.0",
    "@gorhom/bottom-sheet": "^4.5.1",
    "@intercom/intercom-react-native": "^6.3.0",
    "@notifee/react-native": "^7.8.2",
    "@react-native-async-storage/async-storage": "1.18.2",
    "@react-native-community/datetimepicker": "7.2.0",
    "@react-native-community/netinfo": "9.3.10",
    "@react-native-firebase/analytics": "^18.3.0",
    "@react-native-firebase/app": "^18.3.0",
    "@react-native-firebase/messaging": "^18.3.0",
    "@react-native-picker/picker": "2.4.10",
    "@react-native/metro-config": "^0.73.2",
    "@react-navigation/bottom-tabs": "^6.5.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/native-stack": "^6.9.17",
    "@react-navigation/stack": "^6.3.20",
    "@reduxjs/toolkit": "^2.0.1",
    "@segment/analytics-react-native": "^2.17.0",
    "@segment/analytics-react-native-plugin-firebase": "0.3.11",
    "@segment/sovran-react-native": "^1.0.4",
    "@types/react-native-signature-capture": "^0.4.6",
    "add": "^2.0.6",
    "axios": "^1.6.3",
    "date-fns": "^3.2.0",
    "expo": "~49.0.21",
    "expo-application": "~5.3.0",
    "expo-barcode-scanner": "~12.5.3",
    "expo-build-properties": "~0.8.3",
    "expo-camera": "~13.4.4",
    "expo-clipboard": "~4.3.1",
    "expo-constants": "~14.4.2",
    "expo-crypto": "~12.4.1",
    "expo-dev-client": "~2.4.12",
    "expo-device": "~5.4.0",
    "expo-document-picker": "~11.5.4",
    "expo-file-system": "~15.4.5",
    "expo-image-picker": "~14.3.2",
    "expo-linear-gradient": "~12.3.0",
    "expo-linking": "~5.0.2",
    "expo-local-authentication": "~13.4.1",
    "expo-media-library": "~15.4.1",
    "expo-notifications": "~0.20.1",
    "expo-screen-capture": "~5.3.0",
    "expo-secure-store": "~12.3.1",
    "expo-splash-screen": "~0.20.5",
    "expo-status-bar": "~1.6.0",
    "expo-updates": "~0.18.19",
    "expo-web-browser": "~12.3.2",
    "formik": "^2.4.5",
    "immer": "^10.0.3",
    "jest-expo": "^49.0.0",
    "libphonenumber-js": "^1.10.53",
    "lodash-es": "^4.17.21",
    "lottie-react-native": "5.1.6",
    "omit-deep-lodash": "^1.1.7",
    "patch-package": "^8.0.0",
    "prop-types": "^15.8.1",
    "querystringify": "^2.2.0",
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-blob-util": "^0.19.6",
    "react-native-calendars": "^1.1303.0",
    "react-native-dialog": "^9.3.0",
    "react-native-gesture-handler": "~2.12.0",
    "react-native-get-random-values": "~1.9.0",
    "react-native-header-scroll-view": "^2.0.0",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-datetime-picker": "^17.1.0",
    "react-native-modalize": "^2.1.1",
    "react-native-pager-view": "6.2.0",
    "react-native-paper": "^5.11.5",
    "react-native-pdf": "^6.7.4",
    "react-native-phone-input": "^1.3.7",
    "react-native-reanimated": "~3.3.0",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "4.6.3",
    "react-native-screens": "~3.22.0",
    "react-native-share": "^10.0.2",
    "react-native-signature-capture": "^0.4.12",
    "react-native-vector-icons": "^10.0.3",
    "react-native-walkthrough-tooltip": "^1.5.0",
    "react-native-webview": "13.2.2",
    "react-redux": "^8.1.2",
    "redux": "^4.2.1",
    "redux-persist": "^6.0.0",
    "tinycolor2": "^1.6.0",
    "yup": "^1.3.3"
  },

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [x] I'm not using Pods
- [ ] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
❯ react-native info
info Fetching system and libraries information...
System:
  OS: macOS 14.2.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 75.17 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn: Not Found
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/aimableniyogakiza/.rvm/gems/ruby-2.7.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK: Not Found
IDEs:
  Android Studio: Not Found
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.15.1
    path: /usr/bin/javac
  Ruby:
    version: 3.3.0
    path: /opt/homebrew/opt/ruby/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.6
    wanted: 0.72.6
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found

info React Native v0.73.2 is now available (your project is running on v0.72.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.2
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.72.6
info For more info, check out "https://reactnative.dev/docs/upgrading?os=macos&platform=android".

```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
- From firebase version: `18.0.0` and above to the latest
 ```
    "@react-native-firebase/analytics": "^18.7.3",
    "@react-native-firebase/app": "^18.7.3",
    "@react-native-firebase/messaging": "^18.7.3",

```
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION` : `Y` & `"typescript": "^5.3.3"`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by wmaca-friday** [comment]
It seems not to be limited to expo.
Same happens on `react-native` 0.72.8 with `@react-native-firebase/analytics` 18.7.3.

**Comment by wmaca-friday** [comment]
It seems that increasing the `minSdkVersion` from 23 to 24 and the `targetSdkVersion` from 33 to 34 was enough for us.

**Comment by niyogakiza** [comment]
Thank you @wmaca-friday, it builds successful now on android

**Comment by niyogakiza** [comment]
The issue is resolved, thank you again @wmaca-friday

**Comment by divyangDevX** [comment]
I am geeting the same error while build a release apk.
please provide me any solution for that i already tried everything and tragetSdk and compileSdk are 34, but still not able generate Release APK

**Comment by mikehardy** [comment]
@divyangDevX every project is an individual issue and there is no capacity to troubleshoot the infinite possibilities of ways that each project gets things wrong.

What I do instead is show one clear way to get things correct.

This script is fully automated and goes from `npx react-native init` through adding the react-native-firebase modules and crucially *it builds the android release APK* successfully.

Whatever you are doing is obviously not working, so examine this script, perhaps run it, examine it's output and make your project more like it's output. It should correctly build an android release APK

https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
