### ISSUE TITLE
[🐛] RN@0.74 support?

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-firebase#7788]
Has anybody tested the library with the latest RN@0.74? I've just rapidly tried to upgrade my existing app, which depends on `react-native-firebase` from RN@0.73.6 to RN@0.74.1, and after the upgrade on Android (New Architecture) it tells
> _No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()_

(which, I believe is supposed to happen automatically, thus I assume it fails to initialize for RN@0.74).

Also, what is the status of the new architecture support? With RN@0.73 the library works for me in an app using the new architecture on Android; but if I am not missing anything, it does not work alongside the new arch on iOS. The new arch has been around for a while now, and it is supported by most popular RN libraries... this one not supporting it is quite a bummer.

**Comment by birdofpreyru** [comment]
Ok, I found not yet merged PR #7688, which is related to the init failure.

**Comment by harisbaig100** [comment]
i tried applying the patch from this PR https://github.com/invertase/react-native-firebase/pull/7688 but still the error persists

**Comment by birdofpreyru** [comment]
@harisbaig100 that is a mediocre patch :rofl: Hold on, I have a working patch at hands, just need a bit more time to clean it up before sharing.

**Comment by harisbaig100** [comment]
Sure, please do share it, i'm waiting for that

**Comment by birdofpreyru** [comment]
Here you go:

```diff
diff --git a/node_modules/@react-native-firebase/app/lib/internal/FirebaseModule.js b/node_modules/@react-native-firebase/app/lib/internal/FirebaseModule.js
index b970643..aefdcef 100644
--- a/node_modules/@react-native-firebase/app/lib/internal/FirebaseModule.js
+++ b/node_modules/@react-native-firebase/app/lib/internal/FirebaseModule.js
@@ -36,7 +36,7 @@ export default class FirebaseModule {
     if (firebaseJson) {
       return firebaseJson;
     }
-    firebaseJson = JSON.parse(getAppModule().FIREBASE_RAW_JSON);
+    firebaseJson = JSON.parse(getAppModule().getConstants().FIREBASE_RAW_JSON);
     return firebaseJson;
   }
 
diff --git a/node_modules/@react-native-firebase/app/lib/internal/registry/app.js b/node_modules/@react-native-firebase/app/lib/internal/registry/app.js
index 9456630..a8e7f63 100644
--- a/node_modules/@react-native-firebase/app/lib/internal/registry/app.js
+++ b/node_modules/@react-native-firebase/app/lib/internal/registry/app.js
@@ -53,7 +53,7 @@ export function setOnAppDestroy(fn) {
  */
 export function initializeNativeApps() {
   const nativeModule = getAppModule();
-  const { NATIVE_FIREBASE_APPS } = nativeModule;
+  const { NATIVE_FIREBASE_APPS } = nativeModule.getConstants();
 
   if (NATIVE_FIREBASE_APPS && NATIVE_FIREBASE_APPS.length) {
     for (let i = 0; i < NATIVE_FIREBASE_APPS.length; i++) {
diff --git a/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js b/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
index 03f001c..23d467d 100644
--- a/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
+++ b/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
@@ -65,7 +65,7 @@ function nativeModuleWrapped(namespace, NativeModule, argToPrepend) {
     return NativeModule;
   }
 
-  const properties = Object.keys(NativeModule);
+  const properties = Object.keys(Object.getPrototypeOf(NativeModule));
 
   for (let i = 0, len = properties.length; i < len; i++) {
     const property = properties[i];
```

**Comment by harisbaig100** [comment]
now it says this error

` [TypeError: nativeModule.getConstants is not a function. (In 'nativeModule.getConstants()', 'nativeModule.getConstants' is undefined)]`

can you tell what version of the packages you are using, i'm using these : 

   ```
 "@react-native-firebase/app": "^15.3.0",
    "@react-native-firebase/crashlytics": "^15.3.0",
    "@react-native-firebase/messaging": "^15.3.0",
```

**Comment by harisbaig100** [comment]
updated the @react-native-firebase/app to 19.2 now the patch is applied let me check if it works

**Comment by harisbaig100** [comment]
on pod installation now this issue appears

```
[!] The following Swift pods cannot yet be integrated as static libraries:

The Swift pod `FirebaseCrashlytics` depends upon `FirebaseInstallations`, `GoogleDataTransport`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.

The Swift pod `FirebaseSessions` depends upon `FirebaseCoreExtension`, `FirebaseInstallations`, `GoogleDataTransport`, and `nanopb`, which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.
```

**Comment by birdofpreyru** [comment]
I forgot to mention it here, so far I only tested it for Android.

**Comment by harisbaig100** [comment]
okay ... trying to fix it for ios.

**Comment by hamdij0maa** [comment]
android is not loading it's an instant crash ...

**Comment by birdofpreyru** [comment]
Well, if you just bumped library major version from v15 to v19 chances are it is crashing for unrelated reason, because something had to change with the setup in-between 🤷‍♂️

**Comment by harisbaig100** [comment]
The error is still the same after fixing all the issues

`[Error: No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()]`

**Comment by karimb11** [comment]
0.74 + Bridgeless mode is broken on iOS too.

**Comment by birdofpreyru** [comment]
So yeah... if it does not work for you @harisbaig100 , and you saw ` [TypeError: nativeModule.getConstants is not a function. (In 'nativeModule.getConstants()', 'nativeModule.getConstants' is undefined)]` error with the previous version of the patch... I guess you have the bridgeless mode disabled in your app &mdash; I've just disabled it in mine, because of different issues I found, and now my patch does not quite help :)

**Comment by birdofpreyru** [comment]
This one, presumably, should work both in bridge-less and bridge-enabled modes:
```diff
diff --git a/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js b/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
index 03f001c..bd0a484 100644
--- a/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
+++ b/node_modules/@react-native-firebase/app/lib/internal/registry/nativeModule.js
@@ -65,7 +65,8 @@ function nativeModuleWrapped(namespace, NativeModule, argToPrepend) {
     return NativeModule;
   }
 
-  const properties = Object.keys(NativeModule);
+  let properties = Object.keys(Object.getPrototypeOf(NativeModule));
+  if (!properties.lenght) properties = Object.keys(NativeModule);
 
   for (let i = 0, len = properties.length; i < len; i++) {
     const property = properties[i];
```

**Comment by anujmv** [comment]
this is working

function nativeModuleWrapped(namespace, NativeModule, argToPrepend) {
  const native = NativeModule;
  if (!NativeModule) {
    return NativeModule;
  }

  let properties = Object.keys(Object.getPrototypeOf(NativeModule));
  if (!properties.length) properties = Object.keys(NativeModule);

  // const properties = Object.keys(NativeModule);

  for (let i = 0, len = properties.length; i < len; i++) {
    const property = properties[i];
    if (typeof NativeModule[property] === 'function') {
      native[property] = nativeModuleMethodWrapped(namespace, NativeModule[property], argToPrepend);
    } else {
      native[property] = NativeModule[property];
    }
  }

  return native;
}

**Comment by jieey1140** [comment]
My problem seems to be a different issue, but after upgrading to react-native 0.74.1, auth().onAuthStateChanged doesn't work on hot-reload. 

```
  useEffect(() => {
    console.log({ AuthenticationProvider: 'init.' });
    
    const authListener = auth().onAuthStateChanged(async (firebaseUser) => {
      console.log({ firebaseUser });
      try {
        if (!firebaseUser) {
          setUser(firebaseUser);
          setAuthenticating(false);
        } else {
          const customIdToken = await firebaseUser.getIdToken();
          keystore.set('token', customIdToken);
          setUser(firebaseUser);
          setAuthenticating(false);
        }
      } catch (error) {
        console.error('Auth state change error: ', error);
        setAuthenticating(false);
      }
    });

    return () => authListener();
  }, []);
```

In the above code, it logs up to AuthenticationProvider, but nothing happens inside onAuthStateChanged. If you close and restart the app completely, it works again 🤔

**Comment by birdofpreyru** [comment]
@jieey1140  don’t you have this problem: https://github.com/facebook/react-native/issues/44555? Like everything works at first, but at some moment promises from naive side just do not resolve not reject anymore on JS side?

**Comment by atif089** [comment]
> No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()

Hey folks, 

We're scratching our heads for 3 days now. We're facing this issue even with RN - `^0.73.6` and RNFirebase `^19.0.0`.

I'm on Expo 50 and I do not find `newArchEnabled` anywhere in my codebase, so I assume I'm still using old architecture? Everything works fine for Android, and the error only started on iOS about a couple of days ago.

Any pointers? I'm happy to get it to "just work" for now with 0.73.6 and will patiently wait for a stable update to migrate to 0.74 later.

**Comment by ramonxm** [comment]
My app crashes on Android using react native 0.74.1 and "@react-native-firebase/analytics": "^20.0.0", "@react-native-firebase/app": "^20.0.0", works on iOS.

**Comment by atif089** [comment]
Fixed it (iOS, old architecture only).

We found out that this was somehow lost recently, and adding it back fixed it.

![image](https://github.com/invertase/react-native-firebase/assets/541359/951ddeb6-c9a0-4f5c-9f46-ebf969b8ca05)

**Comment by mikehardy** [comment]
I *believe* react-native-firebase is working fine on react-native 0.74.x, even with new architecture enabled
We can reopen if not

**Comment by abhimanyu-truckx** [comment]
Still facing `No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp()` after the latest `react-native-firebase` package installation on RN 74.2

**Comment by MCKmecik** [comment]
> Still facing No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp() on android
> 
> Config:
> RN 74.2
> react-native-firebase: 20.1.0
> classpath 'com.google.gms:google-services:4.4.2'

@abhimanyu-truckx , have you resolved this issue, please? I have same problem with same versions as yours.

**Comment by abhimanyu-truckx** [comment]
> > Still facing No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp() on android
> > Config:
> > RN 74.2
> > react-native-firebase: 20.1.0
> > classpath 'com.google.gms:google-services:4.4.2'
> 
> @abhimanyu-truckx , have you resolved this issue, please? I have same problem with same versions as yours.

Nope

**Comment by MCKmecik** [comment]
> > > Still facing No Firebase App '[DEFAULT]' has been created - call firebase.initializeApp() on android
> > > Config:
> > > RN 74.2
> > > react-native-firebase: 20.1.0
> > > classpath 'com.google.gms:google-services:4.4.2'
> > 
> > 
> > @abhimanyu-truckx , have you resolved this issue, please? I have same problem with same versions as yours.
> 
> Nope

I just resolved my issue. I incorrectly added the code below in android/build.gradle file instead of android/app/build.gradle.

`apply plugin: 'com.google.gms.google-services'`

Maybe you did the same mistake @abhimanyu-truckx.

**Comment by abhimanyu-truckx** [comment]
Clearing metro cache and gradle clean did the trick

**Comment by cebrakadabra** [comment]
My steps to success after being stuck on that for a couple of days was revisiting the react-native architecture changes.
You want to run the following in your `AppDelegate.mm` in addition or in exchange to `AppDelegate.m`

AppDelegate.mm
```
#import <Firebase.h>

...
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{

    self.moduleName = @"{YOUR_APP_NAME}";
    [FIRApp configure];
    // You can add your custom initial props in the dictionary below.
    // They will be passed down to the ViewController used by React Native.
    self.initialProps = @{};

    return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

```

That will remove the initialization error and successfully record events.
Note: You will need to re-run your ios build in order for it to work.
