### ISSUE TITLE
Messaging - Expo EAS build failed (Android)

### ISSUE THREAD

**Issue by WhidRubeld** [invertase/react-native-firebase#8165]
## Issue

Expo-managed Android project build error using EAS.
The error is due to a conflict with the `expo-notifications` library when setting a manifest parameter.

```
> Task :app:processDebugMainManifest FAILED
See https://developer.android.com/r/studio-ui/build/manifest-merger for more information about the manifest merger.
/home/expo/workingdir/build/android/app/src/debug/AndroidManifest.xml:17:88-137 Error:
	Attribute meta-data#com.google.firebase.messaging.default_notification_color@resource value=(@color/notification_icon_color) from AndroidManifest.xml:17:88-137
	is also present at [:react-native-firebase_messaging] AndroidManifest.xml:40:13-44 value=(@color/white).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
> Task :react-native-firebase_crashlytics:compileDebugJavaWithJavac
Note: /home/expo/workingdir/build/node_modules/@react-native-firebase/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
> Task :react-native-firebase_analytics:compileDebugJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
>
Manifest merger failed : Attribute meta-data#com.google.firebase.messaging.default_notification_color@resource value=(@color/notification_icon_color) from AndroidManifest.xml:17:88-137
  	is also present at [:react-native-firebase_messaging] AndroidManifest.xml:40:13-44 value=(@color/white).
  	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml to override.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org/.
```

Old problem https://github.com/invertase/react-native-firebase/issues/7841

---

### Javascript

<details><summary>Click To Expand</summary>

#### `package.json`:

```json
{
   ...
  "dependencies": {
    ...
    "@react-native-firebase/analytics": "^21.0.0",
    "@react-native-firebase/app": "^21.0.0",
    "@react-native-firebase/crashlytics": "^21.0.0",
    "@react-native-firebase/in-app-messaging": "^21.0.0",
    "@react-native-firebase/installations": "^21.0.0",
    "@react-native-firebase/messaging": "^21.0.0",
    ...
    "expo": "~52.0.7",
    ...
    "expo-notifications": "~0.29.8",
    ...
    "react-native": "0.76.3",
    ...
  },
  ...
}

```

#### `firebase.json` for react-native-firebase v6:

```json
{
  "react-native": {}
}
```

</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
System:
  OS: macOS 15.0.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 87.75 MB / 18.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.9.0
    path: ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm:
    version: 10.1.0
    path: ~/.nvm/versions/node/v20.9.0/bin/npm
  Watchman:
    version: 2022.07.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12483815
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli":
    installed: 15.1.2
    wanted: ^15.1.2
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.76.3
    wanted: 0.76.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [x] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `@react-native-firebase/app": "^21.0.0"`
- **`Firebase` module(s) you're using that has the issue:**
  - `"@react-native-firebase/messaging": "^21.0.0"`
- **Are you using `TypeScript`?**
  - `"typescript": "~5.3.3"`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
You'll need to either alter the config plugin here for messaging or there for expo-notifications to do as it says: add the tools XML namespace to the AndroidManifest file (if not there already) and mark that property as tools:replace

The Expo plugins here are community maintained by interested Expo users, none of the maintainers use Expo so we rely on Expo users to keep them working. Bearing that in mind we'll need a PR from someone that uses it so they test it well and know it works. We can merge and release easily if someone proposes a PR

**Comment by WhidRubeld** [comment]
I was able to solve the problem in the following way

```js
const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * Custom Expo plugin to resolve manifest conflicts with Firebase Messaging.
 * Specifically, this plugin ensures that the meta-data for 
 * `com.google.firebase.messaging.default_notification_color` is correctly 
 * configured with `tools:replace="android:resource"` to prevent build errors.
 */
module.exports = function withNotificationToolsReplace(config) {
  return withAndroidManifest(config, (config) => {
    const androidManifest = config.modResults;

    // Ensure the namespace 'tools' is added to the manifest to support 'tools:replace' attributes
    if (!androidManifest.manifest.$['xmlns:tools']) {
      androidManifest.manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
    }

    const application = androidManifest.manifest.application[0];
    application['meta-data'] ??= []; // Ensure 'meta-data' exists in the application node

    // Check if the meta-data for `default_notification_color` already exists
    const metaData = application['meta-data'].find(
      (item) =>
        item['$']['android:name'] ===
        'com.google.firebase.messaging.default_notification_color'
    );

    if (metaData) {
      // If it exists, add or update the 'tools:replace' attribute to resolve conflicts
      metaData['$']['tools:replace'] = 'android:resource';
    } else {
      // If it does not exist, create the meta-data entry with the required attributes
      application['meta-data'].push({
        $: {
          'android:name': 'com.google.firebase.messaging.default_notification_color',
          'android:resource': '@color/notification_icon_color',
          'tools:replace': 'android:resource',
        },
      });
    }

    // Return the updated config
    return config;
  });
};
```

Similar logic is defined in the library plugin. Apparently, it does not work correctly.

**Comment by mikehardy** [comment]
@WhidRubeld - ah! I just looked at the plugin. In fact it does add the tools namespace and the tools replace, or at least it intends to

> Similar logic is defined in the library plugin. Apparently, it does not work correctly.

I cannot understand why - with an existing plugin that has this specific purpose and is hosted here for community use such that you may eventually benefit from others' work as well, you did not propose a fix to the plugin, but made a new one? If you proposed a PR to the plugin, I'd merge it without question...

**Comment by WhidRubeld** [comment]
@mikehardy Yes, I will do PR this week

**Comment by mikehardy** [comment]
Fantastic! Hopefully it's not too awful, I mean...it existed! It used to work? AndroidManifest hasn't changed that much, it's XML after all... strange it's not working now

**Comment by WhidRubeld** [comment]
Yep, the problem was previously solved as described in the old Issue. With the following dependencies combined:

```
"@react-native-firebase/messaging": "^20.5.0",
"expo-notifications": "0.28.3",
```

After updating to the latest versions - the problem has returned. It would be nice to identify the root of the problem...

**Comment by mikehardy** [comment]
@sylv1ah no update, I imagine if someone (could be you!) examines the expo config plugin here to see why it's not doing it's job and fixes it by submitting a PR, we'll see comments here indicating the same or the issue will close as the linked PR is merged+released

We need a motivated expo person to submit a PR though as expo plugins support is community maintained

Future folks looking for updates, please use the subscribe button and/or add a reaction to the issue, +1s or asking for updates vs posting a PR isn't progress, only posting a PR is progress. Thanks

**Comment by itajenglish** [comment]
+1

**Comment by ktanoooo** [comment]
+1

**Comment by WhidRubeld** [comment]
> Managed to resolve this issue by updating all the react-native-firebase dependencies to:
> 
> ```
>     "@react-native-firebase/analytics": "^21.0",
>     "@react-native-firebase/app": "^21.0",
>     "@react-native-firebase/auth": "^21.0",
>     "@react-native-firebase/database": "^21.0",
>     "@react-native-firebase/messaging": "^21.0",
>     "@react-native-firebase/storage": "^21.0",
> ```

The problem persists for versions 21.6.0 inclusive. I'll try to make MR in the coming days

**Comment by Adam-Schlichtmann** [comment]
I am running into this with `"@react-native-firebase/messaging": "^21.7.1",` on Expo 52. 

Unless I missed it somewhere no PR has been made? @WhidRubeld are you still planning on making one?

**Comment by hugobiais** [comment]
Still running into the same issue with `"@react-native-firebase/messaging": "^21.2.0"` on Expo 51. 
Do you need help with the PR @WhidRubeld ? I'd be happy to help !

**Comment by mikehardy** [comment]
@hugobiais still waiting on someone that uses Expo regularly to determine root cause of the bundled plugin not working and post a PR that fixes it - I will be more than happy to work through review and release collaboration with anyone

**Comment by hugobiais** [comment]
@mikehardy I might have found the root cause. I'm using Expo, and in my `app.config.js`, I'm using the `expo-notifications` plugin and I was setup like this when I was facing the build issue:

```javascript
[
        "expo-notifications",
        {
            icon: "./assets/iconNotifAndroid.png",
            color: "#ffffff",
        },
],
```

Setting the `color: "#ffffff"` in that plugin caused an AndroidManifest.xlm merge error because of the `com.google.firebase.messaging.default_notification_color` being set by default to `'@color/white'` in this [file](https://github.com/invertase/react-native-firebase/blob/94c6a27e6692138cd32394218a492d17d68de0f0/packages/messaging/android/build.gradle#L102) (I'm empirically guessing that's the reason).

I tried removing the `color: "#ffffff"` value from my `expo-notifications` setup, and it worked. However, this is only a temporary fix. @mikehardy what would be the next steps to make a PR to fix this ?

**Comment by mikehardy** [comment]
@hugobiais are you using the Expo config plugin for `@react-native-firebase/messaging` ?

It appears to include the tools:replace that will resolve the error, and allows you to specify the notification icon color as well - so it will need to be configured for the color you want (as it will replace other peer entries in the android manifest merger process, like that for expo-notifications) but should result in a successful build

https://github.com/invertase/react-native-firebase/blob/94c6a27e6692138cd32394218a492d17d68de0f0/packages/messaging/plugin/src/android/setupFirebaseNotifationIcon.ts#L71

**Comment by codygreenhalgh** [comment]
> [@mikehardy](https://github.com/mikehardy) I might have found the root cause. I'm using Expo, and in my `app.config.js`, I'm using the `expo-notifications` plugin and I was setup like this when I was facing the build issue:
> 
> [
>         "expo-notifications",
>         {
>             icon: "./assets/iconNotifAndroid.png",
>             color: "#ffffff",
>         },
> ],
> Setting the `color: "#ffffff"` in that plugin caused an AndroidManifest.xlm merge error because of the `com.google.firebase.messaging.default_notification_color` being set by default to `'@color/white'` in this [file](https://github.com/invertase/react-native-firebase/blob/94c6a27e6692138cd32394218a492d17d68de0f0/packages/messaging/android/build.gradle#L102) (I'm empirically guessing that's the reason).
> 
> I tried removing the `color: "#ffffff"` value from my `expo-notifications` setup, and it worked. However, this is only a temporary fix. [@mikehardy](https://github.com/mikehardy) what would be the next steps to make a PR to fix this ?

Thank you for this, I was hitting my head against a wall and this pointed me in the right direction, never thought a color code here would cause my build to fail.

**Comment by mikehardy** [comment]
@vargajacint I refer all the way back to the first line in my original comment:

> You'll need to either alter the config plugin here for messaging or there for expo-notifications to do as it says: add the tools XML namespace to the AndroidManifest file (if not there already) and mark that property as tools:replace

However it appears to need an update now: if we are adding tools:replace XML namespace and XML attribute for the notification color and it is still happening, then it looks like someone is going to need to work with Expo and get them to do the same where ever they set the notification color.

I need to be clear that we *have* to set it. react-native-firebase works in a bare / non-Expo context so we need to set that attribute. But we are trying to "play nice" by marking it as tools:replace. It appears all setters of that attribute may need to as well.

**Comment by MatkoMilic** [comment]
> [@mikehardy](https://github.com/mikehardy) I might have found the root cause. I'm using Expo, and in my `app.config.js`, I'm using the `expo-notifications` plugin and I was setup like this when I was facing the build issue:
> 
> [
>         "expo-notifications",
>         {
>             icon: "./assets/iconNotifAndroid.png",
>             color: "#ffffff",
>         },
> ],
> Setting the `color: "#ffffff"` in that plugin caused an AndroidManifest.xlm merge error because of the `com.google.firebase.messaging.default_notification_color` being set by default to `'@color/white'` in this [file](https://github.com/invertase/react-native-firebase/blob/94c6a27e6692138cd32394218a492d17d68de0f0/packages/messaging/android/build.gradle#L102) (I'm empirically guessing that's the reason).
> 
> I tried removing the `color: "#ffffff"` value from my `expo-notifications` setup, and it worked. However, this is only a temporary fix. [@mikehardy](https://github.com/mikehardy) what would be the next steps to make a PR to fix this ?

Finally fixed this, thank u!

**Comment by soo9028** [comment]
> I was able to solve the problem in the following way
> 
> const { withAndroidManifest } = require('@expo/config-plugins');
> 
> /**
>  * Custom Expo plugin to resolve manifest conflicts with Firebase Messaging.
>  * Specifically, this plugin ensures that the meta-data for 
>  * `com.google.firebase.messaging.default_notification_color` is correctly 
>  * configured with `tools:replace="android:resource"` to prevent build errors.
>  */
> module.exports = function withNotificationToolsReplace(config) {
>   return withAndroidManifest(config, (config) => {
>     const androidManifest = config.modResults;
> 
>     // Ensure the namespace 'tools' is added to the manifest to support 'tools:replace' attributes
>     if (!androidManifest.manifest.$['xmlns:tools']) {
>       androidManifest.manifest.$['xmlns:tools'] = 'http://schemas.android.com/tools';
>     }
> 
>     const application = androidManifest.manifest.application[0];
>     application['meta-data'] ??= []; // Ensure 'meta-data' exists in the application node
> 
>     // Check if the meta-data for `default_notification_color` already exists
>     const metaData = application['meta-data'].find(
>       (item) =>
>         item['$']['android:name'] ===
>         'com.google.firebase.messaging.default_notification_color'
>     );
> 
>     if (metaData) {
>       // If it exists, add or update the 'tools:replace' attribute to resolve conflicts
>       metaData['$']['tools:replace'] = 'android:resource';
>     } else {
>       // If it does not exist, create the meta-data entry with the required attributes
>       application['meta-data'].push({
>         $: {
>           'android:name': 'com.google.firebase.messaging.default_notification_color',
>           'android:resource': '@color/notification_icon_color',
>           'tools:replace': 'android:resource',
>         },
>       });
>     }
> 
>     // Return the updated config
>     return config;
>   });
> };
> Similar logic is defined in the library plugin. Apparently, it does not work correctly.

so far this was the best solution.

**Comment by kimnagui** [comment]
In my case, the issue was resolved by doing the following:

```typescript
// app.config.ts
const config: ExpoConfig = {
    ....
    notification: {
        icon: './assets/images/notification-icon.png',
        color: '#004EF9',
        iosDisplayInForeground: true
    },
    ....
    plugins: [
        ....
        [
            'expo-notifications',
            {
                icon: './assets/images/notification-icon.png',
                color: '#004EF9'
            }
        ],
        ....
        '@react-native-firebase/app',
        '@react-native-firebase/auth',
        '@react-native-firebase/messaging',
        '@react-native-firebase/crashlytics',
        ....
    ]
}
export default config;
```

I placed the `expo-notifications` plugin above the `react-native-firebase` plugin.
This seems to avoid the issue due to the `!hasMetaData` condition in `@react-native-firebase/messaging/plugin/src/android/setupFirebaseNotification.ts`.

**Comment by alexclinky** [comment]
I still have this error with "expo-notifications": "~0.31.4" and "@react-native-firebase/messaging": "^22.4.0",

**Comment by axelmy318** [comment]
I still have this error with expo-notification 0.32.11.
The plugin is placed before react-native-firebase/app.
Nothing seems to be working. I can't even work around it because the custom plugin to add the meta data value does not work anymore.

**Comment by AfraGngr** [comment]
Still have the error with `"expo-notifications": "~0.32.12".` Changing the plugin order didn’t help. Removing the color property resolved it, but I need the color, so I downgraded to version 0.28.0 and solved it

**Comment by vbriand** [comment]
> I still have this error with expo-notification 0.32.11. The plugin is placed before react-native-firebase/app. Nothing seems to be working. I can't even work around it because the custom plugin to add the meta data value does not work anymore.

You need both to have the `expo-notifications plugin` before `@react-native-firebase/messaging` and the `notification` configuration field set for it to build properly since [the plugin is checking for its presence](https://github.com/invertase/react-native-firebase/blob/a2844d482e3f8ae8e8c7dcc69a540123137e21e5/packages/messaging/plugin/src/android/setupFirebaseNotifationIcon.ts#L62) before adding the metadata that prevents the issue from occurring.

I know this has been [deprecated in Expo 54](https://expo.dev/changelog/sdk-54#deprecations--removals) and it doesn't really make sense to have the configuration field as well as the plugin set, but this shouldn't be an issue anymore once [this PR](https://github.com/invertase/react-native-firebase/pull/8663) gets merged to take this deprecation into account and check for the plugin instead.
