### ISSUE TITLE
[🐛]  Crashlytics deprecation warning using modular: This method is deprecated and will be removed in the next major release as part of move to match Firebase Web modular SDK API. Please use `setAttributes()` instead

### ISSUE THREAD

**Issue by TrejoCode** [invertase/react-native-firebase#8326]
## Issue

When I use crashlytics with the functions: `setAttributes()`, `recordError()`, I got the message:

`This method is deprecated (as well as all React Native Firebase namespaced API) and will be removed in the next major release as part of move to match Firebase Web modular SDK API. Please see migration guide for more details: https://rnfirebase.io/migrating-to-v22 Please use `setAttributes()` instead`

`This method is deprecated (as well as all React Native Firebase namespaced API) and will be removed in the next major release as part of move to match Firebase Web modular SDK API. Please see migration guide for more details: https://rnfirebase.io/migrating-to-v22 Please use `recordError()` instead.`

```tsx
import {getCrashlytics} from '@react-native-firebase/crashlytics';
import type {TypeError} from '@app/ts/error';

const crashlytics = getCrashlytics();

/**
 * @description Registra un error en Crashlytics y Sentry.
 * @param {Error|null} [error=null] - El error a registrar, debe ser una instancia de Error.
 * @param {Object|null} [customAttributes=null] - Atributos personalizados del log.
 * @param {string} [errorName='Error desconocido'] - Nombre asignado al error en Crashlytics.
 */
export const reportError = async ({
  error = null,
  customAttributes = null,
  errorName = 'Error desconocido',
}: TypeError) => {
  try {
    if (error instanceof Error) {
      // Garantizar que customAttributes sea un objeto
      const validCustomAttributes =
        typeof customAttributes === 'object' && customAttributes !== null
          ? customAttributes
          : {};

      // Convertir objetos y arrays a cadenas JSON
      const sanitizedCustomAttributes: {[key: string]: string} = {};
      for (const key in validCustomAttributes) {
        if (Object.prototype.hasOwnProperty.call(validCustomAttributes, key)) {
          const value = validCustomAttributes[key];
          sanitizedCustomAttributes[key] =
            typeof value === 'object' ? JSON.stringify(value) : String(value);
        }
      }

      // Registrar en Crashlytics
      crashlytics.setAttributes(sanitizedCustomAttributes);
      crashlytics.recordError(error, errorName);      
    }
  } catch (catchError: any) {
    console.warn(
      'No fue posible registrar el error:',
      catchError?.message ?? 'Error desconocido',
    );
  }
};
```

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
"dependencies": {
    "@react-native-async-storage/async-storage": "^1.24.0",
    "@react-native-firebase/analytics": "21.10.0",
    "@react-native-firebase/app": "21.10.0",
    "@react-native-firebase/app-distribution": "21.10.0",
    "@react-native-firebase/crashlytics": "21.10.0",
    "@react-native-firebase/remote-config": "21.10.0",        
    "@sentry/react-native": "^6.7.0",
    "react": "18.3.1",    
    "react-native": "0.75.5"
  }
```
</details>

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
react-native: 0.75.5
```

- **Platform that you're experiencing the issue on**:
  - [x] iOS
  - [x] Android
  - [x] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 21.10.0`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Que pena, gracias por el ejemplo concreto y puedo ver que estas usando la version actual, entonces necesitamos indagar

Translation: Looks legit, we'll look into it :-), Saludos

**Comment by elkinjosetm** [comment]
Having the same issue here

**Comment by devartwa** [comment]
Hey guys, any updates? Thank you.

**Comment by nicolascavallin** [comment]
I avoid the warning in this way:

```ts
import {
  crash,
  getCrashlytics,
  log,
  recordError,
  setUserId,
  setCrashlyticsCollectionEnabled,
} from '@react-native-firebase/crashlytics';

const crashlytics_instance = getCrashlytics()

const crashlytics = {
  log: (message: string) => log(crashlytics_instance, message),
  setUserId: (userId: string) => setUserId(crashlytics_instance, userId),
  crash: () => crash(crashlytics_instance),
  recordError: (error: Error, jsErrorName?: string) => recordError(crashlytics_instance, error, jsErrorName),
};

export { crashlytics }
```

and then invoke:

```ts
crashlytics.log("Bla bla bla")
```

**Comment by mikehardy** [comment]
@nicolascavallin all I'm seeing there is that you've taken the new modular API, and added a bunch of code so you can call it like the old API instead of...just calling the new APIs directly? I'm not sure the benefit. If there are still deprecation warnings with the new API that's on us (react-native-firebase maintainers) to fix, but I don't see any value in just shuffling the API around

**Comment by nicolascavallin** [comment]
Hey @mikehardy, I agree about no benefits, but in that way the deprecation warnings are not anymore on my console, while in any other way I still get the warns.

**Comment by mikehardy** [comment]
@nicolascavallin with v21.10.1 release I converted our e2e test suite crashlytics area to all modular calls and was no longer able to reproduce any modular warnings - so I believe if used well (?) crashlytics warnings should be resolved with no extra code needed in regular use. Our e2e test suite may serve as a guide - hopefully it's complete - https://github.com/invertase/react-native-firebase/blob/2f855a6150cc02d9d55873e63320c01424ce6434/packages/crashlytics/e2e/crashlytics.e2e.js#L193-L378

@faljabi I believe it's all working now - I'll need to see exact example code you can still see deprecation warnings with when using react-native-firebase 21.10.1+

**Comment by faljabi** [comment]
I am on 21.10.1 and still see a warning saying use getApp although I am using it already. The warning triggers on crash I noticed.

**Comment by mikehardy** [comment]
@faljabi very curious to see your exact code that triggers the warning, please post it as requested, I can investigate.

**Comment by mikehardy** [comment]
@faljabi that was enough of a clue - that it was on crash - crashlytics will notify analytics internally if you have analytics installed - and it was doing so internally using the old namespaced API! Will fix shortly

https://github.com/invertase/react-native-firebase/blob/5a2942517b071141306d675a8501f7d23d87af55/packages/crashlytics/lib/handlers.js#L99
