### ISSUE TITLE
[🐛] app-check modular API doesn't seem to conform to provided docs

### ISSUE THREAD

**Issue by gigilibala** [invertase/react-native-firebase#8361]
## Issue

Looking at the AppCheck implementation in rnfirebase, it doesn't seem like it follows the docs provided in the rnfirebase.io.

Code snippet from docs is as follows:

```typescript
import { ReactNativeFirebaseAppCheckProvider } from `@react-native-firebase/app-check`;
import { initializeAppCheck  } from `@react-native-firebase/app-check`;

rnfbProvider = new ReactNativeFirebaseAppCheckProvider();
rnfbProvider.configure({
  android: {
    provider: __DEV__ ? 'debug' : 'playIntegrity',
    debugToken: 'some token you have configured for your project firebase web console',
  },
  apple: {
    provider: __DEV__ ? 'debug' : 'appAttestWithDeviceCheckFallback',
    debugToken: 'some token you have configured for your project firebase web console',
  },
  web: {
    provider: 'reCaptchaV3',
    siteKey: 'unknown',
  },
});

const appCheck = initializeAppCheck({ provider: rnfbProvider, isTokenAutoRefreshEnabled

```

However, most I could build (working!) with the rnfirebase API is as follows:

```typescript
import { getApp } from "@react-native-firebase/app";
import getAppCheck, { getToken, initializeAppCheck } from "@react-native-firebase/app-check";

const app = getApp()
const appCheck = getAppCheck(app)

const provider = appCheck.newReactNativeFirebaseAppCheckProvider();
provider.configure({
  android: {
    provider: "debug",
  },
  apple: {
    provider: "debug",
  },
  isTokenAutoRefreshEnabled: true,
});

await initializeAppCheck(app, {
  provider,
});

const token = await getToken(appCheck, false);
if (token.token.length <= 0) {
  throw new Error("AppCheck token was not initialized");
}

```

There are few issues I see:

* `initializeAppCheck` is ought to return an `AppCheck` instance, but the signature shows an `App` instance instead. source: https://github.com/invertase/react-native-firebase/blob/082a1e496cb1f8496f53869d9ab9e6f88ecbdc00/packages/app-check/lib/modular/index.js#L37
* There is no `getAppCheck` exported, but I assume this expected since we need to initialize it through `initializeAppCheck`. right?
* There is no exported `newReactNativeFirebaseAppCheckProvider()` or `ReactNativeFirebaseAppCheckProvider`. This is a problem because in order to initialize the appCheck I'd need the result of provider.configure, but currently I need the appCheck instance to get build the provider.

I maybe wrong in all above (and hence these are expected API), but these are observations I just had. Appreciate if I can get feedback whether assumptions above are correct or not.

Thanks.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by mikehardy** [comment]
Was just in this area, using our e2e tests as the proof of it working - I think you may be right about the `initializeAppCheck` not returning the correct type in the typings, but it returns an AppCheck instance in reality, here's what I see working correctly in our e2e tests, all platforms:

https://github.com/invertase/react-native-firebase/blob/082a1e496cb1f8496f53869d9ab9e6f88ecbdc00/packages/app-check/e2e/appcheck.e2e.js#L371-L405

**Comment by gigilibala** [comment]
Hi,
Thanks for the response.
How about the `ReactNativeFirebaseAppCheckProvider`? It doesn't seem to have been exported properly.

<img width="364" alt="Image" src="https://github.com/user-attachments/assets/9072040f-928b-4271-b788-31c2662df3a9" />

**Comment by mikehardy** [comment]
You're correct - sorry about that - when I was in there I exported the implementation, so it works in javascript but the types are definitely not correct so typescript won't buy it.

You could ts-ignore the import line temporarily (maybe have a second one to just ts-ignore this specific import...) and just

```javascript
import { ReactNativeFirebaseAppCheckProvider } from `@react-native-firebase/app`
```

and it *will* work to then `new ReactNativeFirebaseAppCheckProvider();` until I fix the types. My e2e test shows it works at least, just doesn't type check.

You cannot get rid of the `getAppCheck` namespaced import until I fix the modular implementation error and return AppCheck from initializeAppCheck, as that's also a mistake (thanks for pointing it out)

should conform to https://firebase.google.com/docs/reference/js/app-check.md#initializeappcheck_5548dfc and return AppCheck type

Will post a PR to fix that when I get a moment, and tag this issue with it for close

**Comment by wneel** [comment]
Still Relevant

**Comment by mikehardy** [comment]
Yep - got auth (or most of auth) earlier today, will get this one next I hope

**Comment by MichaelVerdon** [comment]
I have a PR out that should fix the issue.

**Comment by mikehardy** [comment]
PR mentioned is now merged and released

**Comment by gimi-anders** [comment]
I still get the same typescript error when I do `new ReactNativeFirebaseAppCheckProvider();`.
I am using firebase version 23.8.2.
@MichaelVerdon is this really fixed or am I missing something?

**Comment by mikehardy** [comment]
If you are using 23.8.2 you are likely not going to be having a good time either way 😓 

- #8829 

However, I'm not aware of app check having problems in the types at the moment - assuming everything is published correctly

Example modular usage like so ? 

https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/e2e/appcheck.e2e.js#L411

**Comment by gimi-anders** [comment]
@mikehardy 
With version 23.8.2 I get this error:

<img width="1055" height="63" alt="Image" src="https://github.com/user-attachments/assets/357fc9b0-c937-425b-9670-96803e583373" />


However it works fine in version 23.7.0. So maybe it will work again when the fix in 23.8.3 is out?

**Comment by lucasbasquerotto** [comment]
@gimi-anders Are you doing something like `import type { ReactNativeFirebaseAppCheckProvider } from ...`. If this is the case, just remove the `type` from the import. Or maybe it's being imported from the wrong place.

**Comment by gimi-anders** [comment]
> [@gimi-anders](https://github.com/gimi-anders) Are you doing something like `import type { ReactNativeFirebaseAppCheckProvider } from ...`. If this is the case, just remove the `type` from the import. Or maybe it's being imported from the wrong place.

@lucasbasquerotto 
No I am not importing it as a type. I am importing it like a normal import, as I have always been doing.
```
import {
  ReactNativeFirebaseAppCheckProvider,
} from "@react-native-firebase/app-check";
```

As I mentioned, it works fine in 23.7.0, so it must either be related to the bug @mikehardy mentioned above, or some export has changed in 23.8.0.

**Comment by mikehardy** [comment]
knowing it is a regression from 23.7.0 vs 23.8.x is important, app-check was migrated to typescript and had all it's exports re-done. Apparently in a regressive way. There is a PR open as well related to updating app-check docs. I'm going to reopen this one to track the regression since it has the best info, and will keep it in mind as I am preening the exports of our typescript-migrated packages as the current task here

**Comment by jsg2021** [comment]
~~I'm still unable to use 23.8.x app-check because of this.~~

**Correction:** I can use it; however, I have to do this:
```ts
import { ReactNativeFirebaseAppCheckProvider } from '@react-native-firebase/app-check';
// @ts-expect-error 
const appCheck: ReactNativeFirebaseAppCheckProvider = new ReactNativeFirebaseAppCheckProvider();
```

1) To mark the import as used, so my import organizer does not delete it, add an explicit type annotation on the variable
2) add `@ts-expect-error` to make tsc not fail for now (and will fail once this is resolved)

**Comment by eyupk3** [comment]
"expo": "~54.0.33", - firebase ^24.0.0 Same problem

**Comment by arthurkonrath-ip4y** [comment]
I am having same problem with firebase 24.0.0.

react native bare.

**Comment by russellwheatley** [comment]
This has been resolved by this refactor #8889 , merged for the v25.0.0 release. Closing out.
