### ISSUE TITLE
[🐛] Property 'firebase' doesn't exist 😱

### ISSUE THREAD

**Issue by birdofpreyru** [invertase/react-native-firebase#8375]
## Issue

The latest v21.11.0 version of the lib, after upgrading to its new, modular API, inside the `database` lib module:
![Image](https://github.com/user-attachments/assets/e88ad501-4a39-43f0-a39a-fb723acea79c)

I also see, there is the same error just above, at the line 112 of that file.

---

### Javascript

<details><summary>Click To Expand</summary>
<p>

#### `package.json`:

```json
# N/A
```

#### `firebase.json` for react-native-firebase v6:

```json
# N/A
```

</details>

### iOS

<details><summary>Click To Expand</summary>
<p>

#### `ios/Podfile`:

- [ ] I'm not using Pods
- [x] I'm using Pods and my Podfile looks like:

```ruby
# N/A
```

#### `AppDelegate.m`:

```objc
// N/A
```

</p>
</details>

---

### Android

<details><summary>Click To Expand</summary>
<p>

#### Have you converted to AndroidX?

- [ ] my application is an AndroidX application?
- [ ] I am using `android/gradle.settings` `jetifier=true` for Android compatibility?
- [ ] I am using the NPM package `jetifier` for react-native compatibility?

#### `android/build.gradle`:

```groovy
// N/A
```

#### `android/app/build.gradle`:

```groovy
// N/A
```

#### `android/settings.gradle`:

```groovy
// N/A
```

#### `MainApplication.java`:

```java
// N/A
```

#### `AndroidManifest.xml`:

```xml
<!-- N/A -->
```

</p>
</details>

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
 OUTPUT GOES HERE
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [ ] Both
- **`react-native-firebase` version you're using that has this issue:**
  - `e.g. 5.4.3`
- **`Firebase` module(s) you're using that has the issue:**
  - `e.g. Instance ID`
- **Are you using `TypeScript`?**
  - `Y/N` & `VERSION`

</p>
</details>

---

- 👉 Check out [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter for updates on the library.

**Comment by MichaelVerdon** [comment]
I have released a PR that should fix this, thanks for your ticket.

**Comment by Nantris** [comment]
We're still seeing this in `@react-native-firebase/database@21.12.0`

When calling `serverTimestamp` we get the error: "Property 'firebase' doesn't exist"

It worked fine for us in `21.7.1`.

Thanks for your work on this @MichaelVerdon - I wonder if you have any thoughts about an underlying cause here?

**Comment by Nantris** [comment]
@birdofpreyru I wonder if this is fixed for you? It would seem strange that the PR would fix `increment` but not fix (or possibly even break?) `serverTimeStamp`.

**Comment by birdofpreyru** [comment]
@Nantris I don’t know, when I bumped into the problem, I worked it around by taking `increment` from the old, default export, and never arrived to try its new export again 😅

**Comment by Nantris** [comment]
Thanks for your reply!

Just wanted to update that `21.9.x` also seems to have this issue. `21.7.x` didn't have this problem. I haven't tested `21.8.0`.

@mikehardy I think something is wrong here beyond what #8377 tried to addressed.

**Comment by mikehardy** [comment]
Reopening to make sure we take a look

**Comment by Nantris** [comment]
Ah I see! My mistake. It's very possible this is fixed then. I'll keep an eye out for the next release. Thanks so much!

**Comment by mikehardy** [comment]
The new version of react-native-firebase with most of the fixes is out - there are still some fixes to work through but...hopefully this fixes up the firebase issues, if not will do a quick follow-on
