### ISSUE TITLE
Error: 400: Your project does not own Dynamic Links domain:

### ISSUE THREAD

**Issue by Luckygirlllll** [invertase/react-native-firebase#998]
### Issue
Getting an error: "Error: 400: Your project does not own Dynamic Links domain:" while try to create short dynamic link, when create usual link, it works fine!   

Code for the creating short dynamic link: 

```
onClickShare= () => {
const link =
    new firebase.links.DynamicLink(redirectLink , Config.FIREBASE_CONFIG.dynamicLink)
      .android.setPackageName(Config.ANDROID_PACKAGE_NAME)
      .ios.setBundleId(Config.IOS_BUNDLE_ID)
      .ios.setAppStoreId(Config.IOS_APP_STORE_ID)
      .social.setDescriptionText(description)
      .social.setTitle(this.props.event.title)

      firebase.links()
      .createShortDynamicLink(link, 'SHORT')
      .then((url) => {
      Share.share({
        message: _('shareLinkMessage') + " " + url,
        title: _('shareLinkTitle'),
       }, {
        // Android only:
        dialogTitle:  _('shareLinkAndroid'),
        })
      })  
```

### Environment

Android

1. Application Target Platform:
macOS Sierra

2. Development Operating System:

Xcode 10.2
Android studio 3.0.1

4. React Native version:
0.47.2

5. RNFirebase Version:
4.0.3

6. Firebase Module:

dynamic links

**Comment by Salakar** [comment]
@Luckygirlllll I think you need to verify the custom domain you're using for your links on the Firebase console

**Comment by Luckygirlllll** [comment]
@Salakar 

What do you mean by "verify" ? Here is the custom domain for the dynamic links in Firebase console 

<img width="399" alt="screen shot 2018-04-22 at 13 11 55" src="https://user-images.githubusercontent.com/10096433/39093851-d32e5ebe-462e-11e8-9b7d-da07659de303.png">

**Comment by chrisbianca** [comment]
I'm going to assume that this is now fixed as we've heard no more from you.  Please re-open with further information if that's not the case.

**Comment by Luckygirlllll** [comment]
Issue is not solved yet, I'm just not using short links in the project, because they don't work in Android

**Comment by supritha** [comment]
@chrisbianca - We have added custom domain and got the right api-key. How should we configure a project for Dynamic Links? 
{
    "error": {
        "code": 400,
        "message": "Your project has not configured Dynamic Links. [https://firebase.google.com/docs/dynamic-links/rest#before_you_begin]",
        "status": "INVALID_ARGUMENT"
    }
}

**Comment by thanh90** [comment]
short dynamic link just doesn't work. long link is ok -__-. using rnfirebase 5.5.6

**Comment by mikron123** [comment]
any solution?

**Comment by Luckygirlllll** [comment]
@mikron123 you can try this solution, helped to me https://stackoverflow.com/questions/49903797/error-400-your-project-does-not-own-dynamic-links-domain/52421563#52421563

**Comment by surya8690** [comment]
Please update your link URL

https://yourDomain?WXYZ?d=1

To

https://yourDomain/WXYZ?d=1

**Comment by Pandit2903** [comment]
![image](https://github.com/invertase/react-native-firebase/assets/61461903/b29d2b6c-6c7d-4006-8dda-6f3314f549d2)
 
 from here add URL pattern like this =>   ^https://.*.com/.*$ 
 
 and try
